Repository Automattic/themes, pull requests merged in 2019-05, with the labels that each got.

#774 Multiple Themes: Fix build-tool vulnerability
  calm-business/package-lock.json
  calm-business/package.json
  calm-business/style-rtl.css
  calm-business/style.css
  elegant-business/package-lock.json
  elegant-business/package.json
  friendly-business/package-lock.json
  friendly-business/package.json
  modern-business/package-lock.json
  modern-business/package.json
  modern-business/style-rtl.css
  modern-business/style.css
  professional-business/package-lock.json
  professional-business/package.json
  sophisticated-business/package-lock.json
  sophisticated-business/package.json
Labels: [Pri] High, bug, has patch, needs testing

#770 Add 32px vertical margin between blocks in all 6 theme variations.
  calm-business/package-lock.json
  calm-business/sass/blocks/_blocks.scss
  calm-business/sass/site/primary/_posts-and-pages.scss
  calm-business/sass/variables-site/_structure.scss
  calm-business/style-rtl.css
  calm-business/style.css
  elegant-business/package-lock.json
  elegant-business/sass/blocks/_blocks.scss
  elegant-business/sass/variables-site/_structure.scss
  elegant-business/style-rtl.css
  elegant-business/style.css
  friendly-business/package-lock.json
  friendly-business/sass/blocks/_blocks.scss
  friendly-business/sass/variables-site/_structure.scss
  friendly-business/style-rtl.css
  friendly-business/style.css
  modern-business/package-lock.json
  modern-business/sass/blocks/_blocks.scss
  modern-business/sass/site/primary/_posts-and-pages.scss
  modern-business/sass/variables-site/_structure.scss
  modern-business/style-rtl.css
  modern-business/style.css
  professional-business/package-lock.json
  professional-business/sass/blocks/_blocks.scss
  professional-business/sass/site/primary/_posts-and-pages.scss
  professional-business/sass/variables-site/_structure.scss
  professional-business/style-rtl.css
  professional-business/style.css
  sophisticated-business/package-lock.json
  sophisticated-business/sass/blocks/_blocks.scss
  sophisticated-business/sass/site/primary/_posts-and-pages.scss
  sophisticated-business/sass/variables-site/_structure.scss
  sophisticated-business/style-editor.scss
  sophisticated-business/style-rtl.css
  sophisticated-business/style.css
Labels: [Pri] Normal, enhancement, needs testing

#790 Temp. fix for Jetpack Business Hours Block style for all 6 style variations
  calm-business/style-editor.css
  calm-business/style-editor.scss
  calm-business/style-jetpack.css
  calm-business/style-jetpack.scss
  elegant-business/style-editor.css
  elegant-business/style-editor.scss
  elegant-business/style-jetpack.css
  elegant-business/style-jetpack.scss
  friendly-business/style-editor.css
  friendly-business/style-editor.scss
  friendly-business/style-jetpack.css
  friendly-business/style-jetpack.scss
  modern-business/style-editor.css
  modern-business/style-editor.scss
  modern-business/style-jetpack.css
  modern-business/style-jetpack.scss
  professional-business/style-editor.css
  professional-business/style-editor.scss
  professional-business/style-jetpack.css
  professional-business/style-jetpack.scss
  sophisticated-business/style-editor.css
  sophisticated-business/style-editor.scss
  sophisticated-business/style-jetpack.css
  sophisticated-business/style-jetpack.scss
Labels: [Pri] Normal, enhancement, needs testing

#791 Temp style enhancements for Mailchimp block for all 6 style variations
  calm-business/style-editor.css
  calm-business/style-editor.scss
  calm-business/style-jetpack.css
  calm-business/style-jetpack.scss
  elegant-business/style-editor.css
  elegant-business/style-editor.scss
  elegant-business/style-jetpack.css
  elegant-business/style-jetpack.scss
  friendly-business/style-editor.css
  friendly-business/style-editor.scss
  friendly-business/style-jetpack.css
  friendly-business/style-jetpack.scss
  modern-business/style-editor.css
  modern-business/style-editor.scss
  modern-business/style-jetpack.css
  modern-business/style-jetpack.scss
  professional-business/style-editor.css
  professional-business/style-editor.scss
  professional-business/style-jetpack.css
  professional-business/style-jetpack.scss
  sophisticated-business/style-editor.css
  sophisticated-business/style-editor.scss
  sophisticated-business/style-jetpack.css
  sophisticated-business/style-jetpack.scss
Labels: [Pri] Normal, enhancement, needs testing

#793 Sophisticated Business: Fix centred image
  sophisticated-business/sass/blocks/_blocks.scss
  sophisticated-business/style.css
Labels: [Pri] Normal, needs testing

#795 Reduce the height and font size for cover block in Modern and Sophisticated Business
  modern-business/sass/blocks/_blocks.scss
  modern-business/style.css
  sophisticated-business/sass/blocks/_blocks.scss
  sophisticated-business/style.css
Labels: enhancement, needs testing

#794 Fix centred align block for Sophisticated and Professional Business
  professional-business/sass/blocks/_blocks.scss
  professional-business/style.css
  sophisticated-business/sass/blocks/_blocks.scss
  sophisticated-business/style-rtl.css
  sophisticated-business/style.css
Labels: [Pri] Normal, needs testing

#796 Fix overflowing centred image in multiple themes
  calm-business/sass/blocks/_blocks.scss
  calm-business/style-jetpack.css
  calm-business/style-rtl.css
  calm-business/style.css
  friendly-business/sass/blocks/_blocks.scss
  friendly-business/style-jetpack.css
  friendly-business/style.css
  modern-business/sass/blocks/_blocks.scss
  modern-business/style-jetpack.css
  modern-business/style-rtl.css
  modern-business/style.css
  sophisticated-business/sass/blocks/_blocks.scss
  sophisticated-business/style-jetpack.css
  sophisticated-business/style-rtl.css
  sophisticated-business/style.css
Labels: [Pri] Normal, bug, needs testing

#797 Multiple Themes: Fixes spacing between columns in all theme variations.
  calm-business/sass/blocks/_blocks.scss
  calm-business/style-rtl.css
  calm-business/style.css
  elegant-business/sass/blocks/_blocks.scss
  elegant-business/style-rtl.css
  elegant-business/style.css
  friendly-business/sass/blocks/_blocks.scss
  friendly-business/style-rtl.css
  friendly-business/style.css
  modern-business/sass/blocks/_blocks.scss
  modern-business/style-rtl.css
  modern-business/style.css
  professional-business/sass/blocks/_blocks.scss
  professional-business/style-rtl.css
  professional-business/style.css
  sophisticated-business/sass/blocks/_blocks.scss
  sophisticated-business/style-rtl.css
  sophisticated-business/style.css
Labels: [Pri] Normal, bug, needs testing

#808 All Theme Variations: fixes Cover Block text align and font-size settings
  calm-business/sass/blocks/_blocks.scss
  calm-business/style-editor.css
  calm-business/style-editor.scss
  calm-business/style-rtl.css
  calm-business/style.css
  elegant-business/sass/blocks/_blocks.scss
  elegant-business/sass/typography/_headings.scss
  elegant-business/style-editor.css
  elegant-business/style-editor.scss
  elegant-business/style-rtl.css
  elegant-business/style.css
  friendly-business/sass/blocks/_blocks.scss
  friendly-business/sass/typography/_headings.scss
  friendly-business/style-rtl.css
  friendly-business/style.css
  modern-business/sass/blocks/_blocks.scss
  modern-business/sass/site/primary/_archives.scss
  modern-business/sass/site/primary/_posts-and-pages.scss
  modern-business/sass/typography/_headings.scss
  modern-business/style-editor.css
  modern-business/style-editor.scss
  modern-business/style-rtl.css
  modern-business/style.css
  professional-business/sass/blocks/_blocks.scss
  professional-business/sass/typography/_headings.scss
  professional-business/style-rtl.css
  professional-business/style.css
  sophisticated-business/sass/blocks/_blocks.scss
  sophisticated-business/sass/typography/_headings.scss
  sophisticated-business/style-editor.css
  sophisticated-business/style-editor.scss
  sophisticated-business/style-rtl.css
  sophisticated-business/style.css
Labels: [Pri] High, bug, in-progress, needs testing

#819 Calm Business: Fixing font sizes for Cover block
  calm-business/sass/blocks/_blocks.scss
  calm-business/style-rtl.css
  calm-business/style.css
Labels: [Pri] Normal, bug, enhancement

#820 Elegant Business: Fixing font sizes in Cover Block
  elegant-business/sass/blocks/_blocks.scss
  elegant-business/style-rtl.css
  elegant-business/style.css
Labels: [Pri] Normal, bug, enhancement

#821 Modern Business: Fix font sizes for Cover Block
  modern-business/sass/blocks/_blocks.scss
  modern-business/style-rtl.css
  modern-business/style.css
Labels: [Pri] Normal, bug, enhancement

#822 Professional Business: Fix font sizes for Cover Block
  professional-business/sass/blocks/_blocks.scss
  professional-business/style-rtl.css
  professional-business/style.css
Labels: [Pri] Normal, bug, enhancement

#823 Professional Business: Fixing font weight for headings in cover block
  professional-business/sass/blocks/_blocks.scss
  professional-business/style-rtl.css
  professional-business/style.css
Labels: [Pri] Normal, bug, enhancement

#825 Sophisticated Business: Fixing font-weight for legacy cover block
  sophisticated-business/sass/blocks/_blocks.scss
  sophisticated-business/style-rtl.css
  sophisticated-business/style.css
Labels: [Pri] Normal, bug, enhancement

#817 All style variations: Add style for posts list block
  calm-business/sass/blocks/_blocks.scss
  calm-business/style-rtl.css
  calm-business/style.css
  elegant-business/sass/blocks/_blocks.scss
  elegant-business/style-rtl.css
  elegant-business/style.css
  friendly-business/sass/blocks/_blocks.scss
  friendly-business/style-rtl.css
  friendly-business/style.css
  modern-business/sass/blocks/_blocks.scss
  modern-business/style-rtl.css
  modern-business/style.css
  professional-business/sass/blocks/_blocks.scss
  professional-business/style-rtl.css
  professional-business/style.css
  sophisticated-business/sass/blocks/_blocks.scss
  sophisticated-business/style-rtl.css
  sophisticated-business/style.css
Labels: [Pri] Normal, enhancement, has patch

#827 All style variations: Add a utility css class for spacer block
  calm-business/sass/blocks/_blocks.scss
  calm-business/style-rtl.css
  calm-business/style.css
  elegant-business/sass/blocks/_blocks.scss
  elegant-business/style-rtl.css
  elegant-business/style.css
  friendly-business/sass/blocks/_blocks.scss
  friendly-business/style-rtl.css
  friendly-business/style.css
  modern-business/sass/blocks/_blocks.scss
  modern-business/style-rtl.css
  modern-business/style.css
  professional-business/sass/blocks/_blocks.scss
  professional-business/style-rtl.css
  professional-business/style.css
  sophisticated-business/sass/blocks/_blocks.scss
  sophisticated-business/style-rtl.css
  sophisticated-business/style.css
Labels: needs testing

#828 Multiple Themes: Fix column block responsive pattern
  calm-business/sass/blocks/_blocks.scss
  calm-business/sass/mixins/_utilities.scss
  calm-business/sass/variables-site/_structure.scss
  calm-business/style-rtl.css
  calm-business/style.css
  elegant-business/sass/blocks/_blocks.scss
  elegant-business/style-rtl.css
  elegant-business/style.css
  friendly-business/sass/blocks/_blocks.scss
  friendly-business/sass/mixins/_utilities.scss
  friendly-business/sass/variables-site/_structure.scss
  friendly-business/style-rtl.css
  friendly-business/style.css
  modern-business/sass/blocks/_blocks.scss
  modern-business/sass/mixins/_utilities.scss
  modern-business/sass/variables-site/_structure.scss
  modern-business/style-rtl.css
  modern-business/style.css
  professional-business/sass/blocks/_blocks.scss
  professional-business/style-rtl.css
  professional-business/style.css
  sophisticated-business/sass/blocks/_blocks.scss
  sophisticated-business/sass/mixins/_utilities.scss
  sophisticated-business/sass/variables-site/_structure.scss
  sophisticated-business/style-rtl.css
  sophisticated-business/style.css
Labels: needs testing
