Repository Automattic/themes, pull requests merged in 2019-12, with the labels that each got.

#1690 Hever: Add FSE support.
  hever/package-lock.json
  hever/sass/_extra-child-theme.scss
  hever/sass/_full-site-editing-editor.scss
  hever/sass/_full-site-editing.scss
  hever/sass/style-child-theme-editor.scss
  hever/sass/style-child-theme.scss
  hever/style-editor.css
  hever/style-rtl.css
  hever/style.css
  varia/style-rtl.css
Labels: FSE Support

#1694 Build FSE themes again
  alves/package-lock.json
  alves/style-editor.css
  alves/style-rtl.css
  alves/style.css
  exford/package-lock.json
  exford/style-editor.css
  exford/style-rtl.css
  exford/style.css
  maywood/package-lock.json
  maywood/style-editor.css
  maywood/style-rtl.css
  maywood/style.css
  shawburn/package-lock.json
  shawburn/style-editor.css
  shawburn/style-rtl.css
  shawburn/style.css
Labels: FSE Support

#1684 Morden: Add Full Site Editing support
  morden/header.php
  morden/languages/morden.pot
  morden/package-lock.json
  morden/package.json
  morden/sass/_full-site-editing-editor.scss
  morden/sass/_full-site-editing.scss
  morden/sass/style-child-theme-editor.scss
  morden/sass/style-child-theme.scss
  morden/style-editor.css
  morden/style-rtl.css
  morden/style.css
  varia/style-editor.css
Labels: FSE Support, [Team] Cylon, varia

#1680 Stow: Add FSE support
  stow/header.php
  stow/package-lock.json
  stow/sass/_extra-child-theme.scss
  stow/sass/_full-site-editing-editor.scss
  stow/sass/_full-site-editing.scss
  stow/sass/_site-navigation.scss
  stow/sass/style-child-theme-editor.scss
  stow/sass/style-child-theme.scss
  stow/style-editor.css
  stow/style-rtl.css
  stow/style.css
Labels: FSE Support, enhancement

#1698 Bump Stow to 1.4.0
  stow/languages/stow.pot
  stow/package-lock.json
  stow/package.json
  stow/sass/style-child-theme.scss
  stow/style-rtl.css
  stow/style.css
Labels: FSE Support

#1660 Varia: Adds support for left, center and right aligned lists.
  varia/sass/blocks/list/_editor.scss
  varia/sass/blocks/list/_style.scss
  varia/style-editor.css
  varia/style.css
Labels: enhancement, varia

#1658 Varia: Remove "Post Type" from Projects Archive title
  varia/inc/template-functions.php
Labels: bug, varia

#1653 Varia: Skip skip-link-focus-fix in AMP
  varia/functions.php
Labels: OSS Citizen, [Status] Ready to Merge, [Theme] Varia

#1729 Button-2: Fix gallery block styles
  button-2/editor-blocks.css
Labels: [Status] Ready to Merge

#1185 Independent Publisher 2: if post word less than 250 words post show 0 minutes time to read solved.
  independent-publisher-2/functions.php
Labels: OSS Citizen, [Status] Ready to Merge
