Repository Automattic/themes, pull requests merged in 2019-02, with the labels that each got.

#111 Pique: Updated SHOW MORE nav item to open on click
  pique/assets/js/navigation.js
  pique/style.css
Labels: [Pri] Normal, needs testing

#479 Radcliffe-2: CSS fix for background of Dropdown menu items leading to same page / page jumps
  .gitignore
  radcliffe-2/style.css
Labels: has patch, needs testing, worksforme

#531 Ixion: Fix cover images with fixed background. See #499
  ixion/blocks.css
Labels: [Pri] High, needs testing

#463 Several themes: Inherit Caption Colours with Gutenberg Blocks
  canard/blocks.css
  gazette/css/blocks.css
  independent-publisher-2/css/blocks.css
  intergalactic-2/blocks.css
  rebalance/blocks.css
Labels: [Pri] Normal, needs testing

#542 Affinity: Fix Gutenberg gallery block when images link to media files
  affinity/blocks.css
Labels: [Pri] High, bug, needs testing

#139 Add Gutenberg blocks XML file to design-toolkit directory.
  design-toolkit/gutenberg-blocks-post.xml
Labels: [Pri] Low

#572 Intergalactic 2: Fixes color annotations so that site title doesn’t disappear
  intergalactic-2/inc/wpcom-colors.php
Labels: [Pri] Normal, needs testing

#370 Libretto: Prevent Title Block Link Overlap with Menu
  libretto/style.css
Labels: [Pri] Normal, needs testing

#581 Altofocus: Fix menu overlap issue
  altofocus/style.css
Labels: [Pri] Normal, needs testing
