Repository Automattic/themes, pull requests merged in 2019-03, with the labels that each got.

#655 Multiple themes: Fixes hard coded column width for Media & Text Block
  friendly-business/sass/blocks/_blocks.scss
  friendly-business/style-rtl.css
  friendly-business/style.css
  modern-business/style-editor.css
  modern-business/style-editor.scss
  professional-business/sass/blocks/_blocks.scss
  professional-business/style-editor.css
  professional-business/style-editor.scss
  professional-business/style-rtl.css
  professional-business/style.css
  sophisticated-business/sass/blocks/_blocks.scss
  sophisticated-business/style-editor.css
  sophisticated-business/style-editor.scss
  sophisticated-business/style-rtl.css
  sophisticated-business/style.css
Labels: [Pri] High, bug, needs testing

#661 Sketch: Updates Flexslider with jQuery output refactor.
  sketch/js/jquery.flexslider.js
Labels: [Pri] High

#663 Dara: Updates Flexslider with jQuery output refactor.
  dara/assets/js/jquery.flexslider.js
Labels: [Pri] High

#665 Toujours: Updates Flexslider with jQuery output refactor.
  toujours/js/jquery.flexslider.js
Labels: [Pri] High

#664 Textbook: Updates Flexslider with jQuery output refactor.
  textbook/assets/js/jquery.flexslider.js
Labels: [Pri] High

#662 Shoreditch: Updates Flexslider with jQuery output refactor.
  shoreditch/js/jquery.flexslider.js
Labels: [Pri] High

#689 Closes #688 - fixes post entry meta width for mobile devices.
  calm-business/sass/site/primary/_posts-and-pages.scss
  calm-business/style.css
  calm-business/style.scss
Labels: [Pri] High, bug, needs testing

#675 All Business Theme Variations: Fixes a compiler issue
  calm-business/package-lock.json
  calm-business/package.json
  calm-business/postcss.config.js
  calm-business/print.css
  calm-business/style-editor.css
  calm-business/style.css
  elegant-business/package-lock.json
  elegant-business/package.json
  elegant-business/postcss.config.js
  elegant-business/print.css
  elegant-business/style-editor.css
  elegant-business/style-rtl.css
  elegant-business/style.css
  friendly-business/package-lock.json
  friendly-business/package.json
  friendly-business/postcss.config.js
  friendly-business/print.css
  friendly-business/style-editor.css
  friendly-business/style-rtl.css
  friendly-business/style.css
  modern-business/package-lock.json
  modern-business/package.json
  modern-business/postcss.config.js
  modern-business/print.css
  modern-business/style-editor.css
  modern-business/style.css
  professional-business/package-lock.json
  professional-business/package.json
  professional-business/postcss.config.js
  professional-business/print.css
  professional-business/style-editor.css
  professional-business/style.css
  sophisticated-business/package-lock.json
  sophisticated-business/package.json
  sophisticated-business/postcss.config.js
  sophisticated-business/print.css
  sophisticated-business/style-editor.css
  sophisticated-business/style.css
Labels: [Pri] Normal, bug
