Repository Automattic/themes, pull requests merged in 2019-07, with the labels that each got.

#1057 Update modern business to support the full site editing plugin header
  modern-business/sass/site/header/_site-header.scss
  modern-business/sass/typography/_headings.scss
  modern-business/style-editor.css
  modern-business/style-editor.scss
  modern-business/style-rtl.css
  modern-business/style.css
Labels: enhancement

#1061 Update the Elegant Business theme to support FSE header
  elegant-business/sass/site/header/_site-header.scss
  elegant-business/sass/typography/_headings.scss
  elegant-business/style-editor.css
  elegant-business/style-editor.scss
  elegant-business/style-rtl.css
  elegant-business/style.css
Labels: enhancement

#1058 Update the Friendly Business theme to support FSE header
  friendly-business/sass/site/header/_site-header.scss
  friendly-business/sass/typography/_headings.scss
  friendly-business/style-editor.css
  friendly-business/style-editor.scss
  friendly-business/style-rtl.css
  friendly-business/style.css
Labels: enhancement

#1077 Update the Calm Business theme to support FSE header
  calm-business/sass/site/header/_site-header.scss
  calm-business/sass/typography/_headings.scss
  calm-business/style-editor.css
  calm-business/style-editor.scss
  calm-business/style-rtl.css
  calm-business/style.css
  sophisticated-business/sass/site/header/_site-header.scss
  sophisticated-business/sass/typography/_headings.scss
  sophisticated-business/style-editor.css
  sophisticated-business/style-editor.scss
  sophisticated-business/style-rtl.css
  sophisticated-business/style.css
Labels: enhancement

#1076 Update the Sophisticated Business theme to support FSE header
  sophisticated-business/sass/site/header/_site-header.scss
  sophisticated-business/sass/typography/_headings.scss
  sophisticated-business/style-editor.css
  sophisticated-business/style-editor.scss
  sophisticated-business/style-rtl.css
  sophisticated-business/style.css
Labels: enhancement, in-progress

#1079 _dsgnsystm: Add support for site-title and site-description in customizer
  _dsgnsystm/functions.php
  _dsgnsystm/inc/customizer.php
Labels: [Pri] High, _dsgnsystm, bug, needs testing

#1082 _dsgnsystm: Fix text-align for H2 in cover block
  _dsgnsystm/sass/blocks/cover/_editor.scss
  _dsgnsystm/sass/blocks/cover/_style.scss
  _dsgnsystm/style-editor.css
  _dsgnsystm/style-rtl.css
  _dsgnsystm/style.css
Labels: [Pri] High, _dsgnsystm, bug, needs testing

#1072 Full Site Editing: Fix post content nested block alignment on modern business
  modern-business/style-editor.css
  modern-business/style-editor.scss
Labels: enhancement

#1078 _dsgnsystm: Fix a11y in mobile menu
  _dsgnsystm/header.php
  _dsgnsystm/package-lock.json
  _dsgnsystm/sass/components/header/_site-main-navigation.scss
  _dsgnsystm/style-rtl.css
  _dsgnsystm/style.css
Labels: [Pri] High, _dsgnsystm, bug, needs testing

#1090 Redhill: Fix fonts in editor to match the frontend
  redhill/sass/style-child-theme-editor.scss
  redhill/style-editor.css
  redhill/style-rtl.css
Labels: [Pri] High, _dsgnsystm, bug, needs testing

#1088 _dsgnsystm: Fix padding for form fields
  _dsgnsystm/sass/elements/_config.scss
  _dsgnsystm/sass/elements/_forms.scss
  _dsgnsystm/style-rtl.css
  _dsgnsystm/style.css
Labels: [Pri] High, _dsgnsystm, needs testing

#1094 Update the Modern Business theme to support FSE footer
  modern-business/inc/fse-template-data.php
  modern-business/sass/site/footer/_site-footer.scss
  modern-business/style-editor.css
  modern-business/style-editor.scss
  modern-business/style-rtl.css
  modern-business/style.css
Labels: enhancement

#1095 _dsgnsystm: Add more vertical space between posts
  _dsgnsystm/sass/layout/_structure.scss
  _dsgnsystm/style-rtl.css
  _dsgnsystm/style.css
Labels: _dsgnsystm

#1092 _dsgnsystm: Fix text-alignment and padding in pullquote block
  _dsgnsystm/sass/blocks/pullquote/_editor.scss
  _dsgnsystm/sass/blocks/pullquote/_style.scss
  _dsgnsystm/sass/blocks/utilities/_style.scss
  _dsgnsystm/style-editor.css
  _dsgnsystm/style-rtl.css
  _dsgnsystm/style.css
Labels: [Pri] High, _dsgnsystm, bug, needs testing

#1098 Update the Modern Business footer to remove code duplication
  modern-business/footer.php
Labels: enhancement

#1102 Varia: Update the screenshot to include the new Varia theme name
  varia/screenshot.png
Labels: _dsgnsystm

#1086 Fix block alignment in FSE context for friendly business
  friendly-business/style-editor.css
  friendly-business/style-editor.scss
Labels: enhancement

#1103 Fix a template conflict issue with modern business
  modern-business/inc/fse-template-data.php
Labels: bug

#1122 Varia: Have links inherit the color only when the block (Media & Text or Paragrpah) are using a background color
  redhill/style-editor.css
  redhill/style-rtl.css
  redhill/style.css
  varia/sass/blocks/_editor.scss
  varia/sass/blocks/media-text/_editor.scss
  varia/sass/blocks/media-text/_style.scss
  varia/sass/blocks/paragraph/_editor.scss
  varia/sass/blocks/paragraph/_style.scss
  varia/style-rtl.css
  varia/style.css
Labels: varia

#1123 Varia: Add posts list block support
  varia/sass/blocks/_editor.scss
  varia/sass/blocks/_imports.scss
  varia/sass/blocks/button/_style.scss
  varia/sass/blocks/posts-list/_editor.scss
  varia/sass/blocks/posts-list/_style.scss
  varia/style-editor.css
  varia/style-rtl.css
  varia/style.css
Labels: [Pri] High, enhancement, needs testing, varia

#1126 Varia: Add missing output the footer menu and change the name of its …
  varia/footer.php
  varia/functions.php
  varia/sass/components/_imports.scss
  varia/sass/components/footer/_footer-branding.scss
  varia/sass/components/footer/_footer-navigation.scss
  varia/sass/components/footer/_footer.scss
  varia/sass/components/widgets/_widgets.scss
  varia/style-rtl.css
  varia/style.css
Labels: [Pri] High, enhancement, needs testing, varia

#1150 Leven: Initial commit
  leven/functions.php
  leven/package-lock.json
  leven/package.json
  leven/postcss.config.js
  leven/print.css
  leven/sass/_config-child-theme-deep.scss
  leven/sass/_config-child-theme.scss
  leven/sass/_extra-child-theme.scss
  leven/sass/print.scss
  leven/sass/style-child-theme-editor.scss
  leven/sass/style-child-theme.scss
  leven/screenshot.png
  leven/style-editor.css
  leven/style-rtl.css
  leven/style.css
Labels: varia

#1147 Varia: Fix responsive logic for better mobile view
  varia/sass/abstracts/_mixins.scss
  varia/sass/abstracts/_responsive-logic.scss
  varia/sass/blocks/cover/_style.scss
  varia/sass/blocks/gallery/_style.scss
  varia/sass/blocks/group/_style.scss
  varia/sass/blocks/pullquote/_style.scss
  varia/style-rtl.css
  varia/style.css
Labels: [Pri] Normal, bug, needs testing, varia

#1148 Varia: Improve spacer blocks on Mobile
  varia/sass/abstracts/_mixins.scss
  varia/sass/blocks/spacer/_style.scss
  varia/style-rtl.css
  varia/style.css
Labels: [Pri] Low, enhancement, needs testing, varia

#1153 Leven: Refactoring the header to be more flexible
  leven/sass/_config-child-theme-deep.scss
  leven/sass/_extra-child-theme.scss
  leven/style-rtl.css
  leven/style.css
  leven/template-parts/header/site-branding.php
Labels: [Pri] Normal, bug, varia

#1155 Leven: Update headstart annotations
  leven/inc/headstart/en.json
Labels: [Pri] Normal, enhancement, varia

#1154 Varia: Simply hides the wpstats image :-)
  varia/sass/components/_imports.scss
  varia/sass/components/utilities/_utilities.scss
  varia/style-rtl.css
  varia/style.css
Labels: [Pri] Normal, enhancement, varia
