Repository Automattic/themes, pull requests merged in 2020-01, with the labels that each got.

#1726 Button-2: Center image caption on frontend
  button-2/blocks.css
  button-2/editor-blocks.css
  button-2/style.css
Labels: [Status] Ready to Merge

#1709 Add ‘wp_body_open’ hook.
  varia/header.php
Labels: OSS Citizen, [Status] Ready to Merge

#1703 Multiple Varia Child Themes: Fix custom-logo support to prevent scaling up too small images.
  dalston/functions.php
  redhill/functions.php
Labels: [Status] Ready to Merge, [Theme] Varia, [Type] Bug

#1661 Mayland: Fix key prop warning in Editor.
  mayland/functions.php
  mayland/sass/_config-child-theme-deep.scss
  mayland/style-editor.css
  mayland/style-rtl.css
  mayland/style-woocommerce-rtl.css
  mayland/style-woocommerce.css
  mayland/style.css
Labels: [Status] Needs Rebase, [Status] Ready to Merge, [Theme] Varia, [Type] Bug

#681 Multiple Themes: Fix Pinterest Icons Not Displaying
  apostrophe-2/style.css
  canard/style.css
  gazette/style.css
  illustratr/style.css
  libretto/style.css
  publication/style.css
  rebalance/style.css
  sketch/style.css
Labels: OSS Citizen, [Status] Needs Review

#584 Dyad 2: Fix fade over short posts on blog page
  dyad-2/js/global.js
Labels: [Pri] Normal, [Status] Needs Testing

#1757 Varia: Fix Faux button style
  varia/sass/base/_extends.scss
  varia/sass/blocks/blog-posts/_style.scss
  varia/sass/blocks/button/_editor.scss
  varia/sass/blocks/button/_style.scss
  varia/style-editor.css
  varia/style-rtl.css
  varia/style-woocommerce-rtl.css
  varia/style-woocommerce.css
  varia/style.css
Labels: [Status] Needs Testing
