Repository Automattic/themes, pull requests merged in 2020-05, with the labels that each got.

#1940 Fix incorrect font name
  hever/functions.php
Labels: [Status] Needs Review, [Type] Bug

#1867 Scratchpad: Fix list view in editor
  scratchpad/editor-blocks.css
Labels: [Status] Needs Testing

#1870 Affinity: Fix list view in editor
  affinity/editor-blocks.css
Labels: [Status] Needs Testing

#1871 AltoFocus: Fix list view in editor
  altofocus/assets/stylesheets/editor-blocks.css
Labels: [Status] Needs Testing

#1872 Apostrophe 2: Fix list view in editor
  apostrophe-2/css/editor-blocks.css
Labels: [Status] Needs Testing

#1873 Canard: Fix list view in editor
  canard/editor-blocks.css
Labels: [Status] Needs Testing

#1874 Dara: Fix list view in editor
  dara/editor-blocks.css
Labels: [Status] Needs Testing

#1875 Intergalactic 2: Fix list view in editor
  intergalactic-2/editor-blocks.css
Labels: [Status] Needs Testing

#1876 Ixion: Fix list view in editor
  ixion/editor-blocks.css
Labels: [Status] Needs Testing

#1877 Karuna: Fix list view in editor
  karuna/editor-blocks.css
Labels: [Status] Needs Testing

#1878 Libretto: Fix list view in editor
  libretto/css/editor-blocks.css
Labels: [Status] Needs Testing

#1879 Publication: Fix list view in editor
  publication/editor-blocks.css
Labels: [Status] Needs Testing

#1880 Rebalance: Fix list view in editor
  rebalance/editor-blocks.css
Labels: [Status] Needs Testing

#1881 Toujours: Fix list view in editor
  toujours/editor-blocks.css
Labels: [Status] Needs Testing

#1949 Maywood: Only apply cover image text shadow if there's a background image or video.
  maywood/sass/_extra-child-theme.scss
  maywood/sass/style-child-theme-editor.scss
  maywood/style-editor.css
  maywood/style-rtl.css
  maywood/style.css
Labels: [Type] Enhancement

#2034 Dyad 2: Refactor editor styles implementation
  dyad-2/css/blocks.css
  dyad-2/css/editor-blocks.css
  dyad-2/functions.php
  dyad-2/style.css
Labels: [Type] Bug

#1884 Varia: Unclosed brackets in SCSS
  varia/sass/components/pagination/_next-previous.scss
  varia/sass/vendors/woocommerce/components/_pagination.scss
Labels: [Status] Needs Testing
