Repository Automattic/themes, pull requests merged in 2020-06, with the labels that each got.

#1942 Radcliffe 2: Fix Social Icons Block alignment
  radcliffe-2/assets/css/blocks.css
Labels: [Status] Needs Testing

#2109 Multiple Themes: Fix nested wide/full blocks
  apostrophe-2/css/blocks.css
  independent-publisher-2/css/blocks.css
  ixion/blocks.css
  libre-2/css/blocks.css
  radcliffe-2/assets/css/blocks.css
Labels: [Type] Bug

#1778 Independent Publisher 2: Fix table cell width issue
  independent-publisher-2/style.css
Labels: [Status] Needs Testing

#1944 Varia: Add Color Annotations
  varia/functions.php
  varia/inc/customize-message-wpcom.css
  varia/inc/customize-message-wpcom.js
  varia/inc/wpcom-colors.php
  varia/inc/wpcom-editor-colors.php
  varia/inc/wpcom.php
  varia/js/customize-preview.js
  varia/sass/blocks/button/_editor.scss
  varia/sass/blocks/button/_style.scss
  varia/sass/blocks/cover/_editor.scss
  varia/sass/blocks/cover/_style.scss
  varia/sass/blocks/separator/_style.scss
  varia/sass/blocks/table/_editor.scss
  varia/sass/blocks/table/_style.scss
  varia/sass/blocks/utilities/_editor.scss
  varia/sass/blocks/utilities/_style.scss
  varia/sass/components/pagination/_next-previous.scss
  varia/style-editor.css
  varia/style-rtl.css
  varia/style.css
Labels: [Type] Enhancement

#2134 Add in-progress sk8prk theme
  sk8prk/assets/js/extend-blocks.js
  sk8prk/assets/sass/_block-extends.scss
  sk8prk/assets/sass/_header.scss
  sk8prk/assets/sass/_responsive.scss
  sk8prk/assets/sass/_text.scss
  sk8prk/assets/sass/block-extends/_button.scss
  sk8prk/assets/sass/block-extends/_cover.scss
  sk8prk/assets/sass/block-extends/_gallery.scss
  sk8prk/assets/sass/block-extends/_group.scss
  sk8prk/assets/sass/block-extends/_image.scss
  sk8prk/assets/sass/block-extends/_latest-posts.scss
  sk8prk/assets/sass/block-extends/_media-text.scss
  sk8prk/assets/sass/block-extends/_pullquote.scss
  sk8prk/assets/sass/style.scss
  sk8prk/functions.php
  sk8prk/header.php
  sk8prk/package-lock.json
  sk8prk/package.json
  sk8prk/style-rtl.css
  sk8prk/style.css
  sk8prk/template-parts/content/content-page.php
  sk8prk/template-parts/content/content-single.php
  sk8prk/variables.css
Labels: [Type] Task

#2135 Seedlet: Create seedlet.pot
  seedlet/languages/seedlet.pot
Labels: [Theme] Seedlet, [Type] Task

#2137 Seedlet: Fix text domain/translation errors
  seedlet/classes/class-seedlet-custom-colors.php
  seedlet/functions.php
Labels: [Type] Bug

#2138 Add a sanitize callback for the custom colors function.
  seedlet/classes/class-seedlet-custom-colors.php
Labels: [Theme] Seedlet, [Type] Bug

#2147 Alves: Fix custom colors logic
  alves/functions.php
Labels: [Type] Bug

#2139 Seedlet: Add body_open function
  seedlet/header.php
Labels: [Type] Bug

#2150 Remove conditional logic to hide navigation scripts.
  seedlet/functions.php
Labels: [Type] Bug

#2153 Restore foreground color rules
  rivington/inc/wpcom-colors.php
  rivington/inc/wpcom-editor-colors.php
  rivington/style-editor.css
  rivington/style-rtl.css
  rivington/style.css
Labels: [Type] Bug

#2152 Shawburn: Reset the non-aligned button block appearance
  shawburn/sass/_extra-child-theme.scss
  shawburn/style-rtl.css
  shawburn/style.css
Labels: [Type] Bug

#2155 Varia/Coutoire/Alves: Restore foreground color rules
  alves/inc/wpcom-editor-colors.php
  alves/style-editor.css
  alves/style-rtl.css
  alves/style.css
  coutoire/inc/wpcom-colors.php
  coutoire/inc/wpcom-editor-colors.php
  coutoire/style-editor.css
  coutoire/style-rtl.css
  coutoire/style.css
  varia/sass/blocks/utilities/_editor.scss
  varia/sass/blocks/utilities/_style.scss
  varia/style-editor.css
  varia/style-rtl.css
  varia/style.css
Labels: [Theme] Varia

#2163 Seedlet: Add focus styles
  seedlet/assets/css/style-editor.css
  seedlet/assets/sass/base/_editor.scss
  seedlet/assets/sass/base/_reset.scss
  seedlet/assets/sass/blocks/blog-posts/_style.scss
  seedlet/assets/sass/components/comments/_comments.scss
  seedlet/assets/sass/components/entry/_header.scss
  seedlet/assets/sass/components/entry/_meta.scss
  seedlet/assets/sass/components/footer/_footer-branding.scss
  seedlet/assets/sass/components/footer/_footer-navigation.scss
  seedlet/assets/sass/components/header/_header-branding.scss
  seedlet/assets/sass/components/header/_primary-navigation.scss
  seedlet/assets/sass/components/header/_social-navigation.scss
  seedlet/assets/sass/components/pagination/_style.scss
  seedlet/style-rtl.css
  seedlet/style.css
Labels: [Theme] Seedlet, [Type] Enhancement

#2165 Seedlet Blocks: Center-align the site title
  seedlet-blocks/block-template-parts/header.html
  seedlet-blocks/style.css
Labels: [Type] Enhancement

#2167 Seedlet Blocks: Add basic global styles support
  seedlet-blocks/experimental-theme.json
  seedlet-blocks/functions.php
  seedlet-blocks/style-editor.css
  seedlet-blocks/style.css
Labels: [Theme] Seedlet Blocks

#2143 Seedlet: fixes logic and warnings around custom colors
  seedlet/assets/css/variables-editor.css
  seedlet/assets/css/variables.css
  seedlet/assets/sass/abstracts/_config.scss
  seedlet/assets/sass/child-theme/variables-editor.css
  seedlet/assets/sass/child-theme/variables.css
  seedlet/classes/class-seedlet-custom-colors.php
Labels: [Theme] Seedlet, [Type] Bug

#2170 Seedlet/Seedlet Blocks: Update repository URL
  seedlet-blocks/style.css
  seedlet/README.md
  seedlet/assets/sass/child-theme/style-child-theme.scss
  seedlet/assets/sass/style.scss
  seedlet/languages/seedlet.pot
  seedlet/style-rtl.css
  seedlet/style.css
Labels: [Type] Bug

#2181 Update Seedlet readme.
  seedlet/README.md
Labels: [Type] Documentation, [Type] Enhancement

#2188 Seedlet: Add vertical spacing logic to widget areas.
  seedlet/assets/sass/structure/_vertical-margins.scss
  seedlet/style-rtl.css
  seedlet/style.css
Labels: [Theme] Seedlet, [Type] Bug

#2198 Seedlet: remove reference to Varia in print styles
  seedlet/assets/css/print.css
  seedlet/assets/sass/print.scss
Labels: [Theme] Seedlet

#2195 Seedlet: Minor version number bump
  seedlet/assets/css/ie.css
  seedlet/assets/sass/style.scss
  seedlet/style-rtl.css
  seedlet/style.css
Labels: [Theme] Seedlet
