Repository Automattic/themes, pull requests merged in 2020-09, with the labels that each got.

#2417 Seedlet: Correct nested color rules
  seedlet/assets/css/ie.css
  seedlet/assets/css/style-editor.css
  seedlet/assets/sass/blocks/cover/_editor.scss
  seedlet/assets/sass/blocks/cover/_style.scss
  seedlet/assets/sass/blocks/utilities/_style.scss
  seedlet/style-rtl.css
  seedlet/style.css
Labels: [Theme] Seedlet, [Type] Bug

#2430 Seedlet: fix escaping function in comments
  seedlet/comments.php
Labels: [Theme] Seedlet

#2422 Add WhatsApp icon to SVG sprite
  varia/classes/class-varia-svg-icons.php
Labels: [Theme] Varia, [Type] Enhancement

#2425 Seedlet: Add translation functions to block-styles.php
  seedlet/inc/block-styles.php
Labels: [Theme] Seedlet, [Type] Bug

#2439 Fix seedlet font translator comments
  seedlet/functions.php
Labels: [Theme] Seedlet

#2436 Seedlet: Add additional gutenberg-related theme tags
  seedlet/assets/css/ie.css
  seedlet/assets/sass/style.scss
  seedlet/style-rtl.css
  seedlet/style.css
Labels: [Theme] Seedlet

#2456 Varia: Removes custom code for dealing with Galleries in varia based themes
  seedlet/assets/sass/blocks/gallery/_style.scss
  varia/sass/blocks/gallery/_style.scss
  varia/style-rtl.css
  varia/style.css
Labels: [Status] Needs Review, [Theme] Seedlet, [Theme] Varia

#2457 Remove custom code for gallery blocks in Seedlet
  seedlet/assets/css/ie.css
  seedlet/assets/sass/blocks/gallery/_style.scss
  seedlet/style.css
Labels: [Status] Needs Review

#2461 Varia: Update children themes
  alves/sass/style-child-theme.scss
  alves/style-rtl.css
  alves/style.css
  balasana/sass/style-child-theme.scss
  balasana/style-rtl.css
  balasana/style.css
  barnsbury/sass/style-child-theme.scss
  barnsbury/style-rtl.css
  barnsbury/style.css
  brompton/package-lock.json
  brompton/sass/style-child-theme.scss
  brompton/style-rtl.css
  brompton/style.css
  coutoire/sass/style-child-theme.scss
  coutoire/style-rtl.css
  coutoire/style.css
  dalston/sass/style-child-theme.scss
  dalston/style-rtl.css
  dalston/style.css
  exford/sass/style-child-theme.scss
  exford/style-rtl.css
  exford/style.css
  hever/sass/style-child-theme.scss
  hever/style-rtl.css
  hever/style.css
  leven/sass/style-child-theme.scss
  leven/style-rtl.css
  leven/style.css
  mayland/sass/style-child-theme.scss
  mayland/style-rtl.css
  mayland/style.css
  maywood/sass/style-child-theme.scss
  maywood/style-rtl.css
  maywood/style.css
  morden/sass/style-child-theme.scss
  morden/style-rtl.css
  morden/style.css
  redhill/sass/style-child-theme.scss
  redhill/style-rtl.css
  redhill/style.css
  rivington/sass/style-child-theme.scss
  rivington/style-rtl.css
  rivington/style.css
  rockfield/sass/style-child-theme.scss
  rockfield/style-rtl.css
  rockfield/style.css
  shawburn/sass/style-child-theme.scss
  shawburn/style-rtl.css
  shawburn/style.css
  stow/sass/style-child-theme.scss
  stow/style-rtl.css
  stow/style.css
  stratford/sass/style-child-theme.scss
  stratford/style-rtl.css
  stratford/style.css
  varia/rebuild-child-themes.sh
Labels: [Status] Needs Review

#2462 #2415 Coutoire: Fixed missing bold font on headings
  coutoire/functions.php
  coutoire/sass/_config-child-theme-deep.scss
  coutoire/sass/style-child-theme.scss
  coutoire/style-editor.css
  coutoire/style-rtl.css
  coutoire/style.css
Labels: [Status] In Progress

#2393 Fixes galleries in Pique
  pique/style.css
Labels: [Status] Needs Review

#2473 #2382 swaped the z-index of the menu buttons to avoid flash
  seedlet/assets/css/ie.css
  seedlet/assets/sass/components/header/_primary-navigation.scss
  seedlet/style-rtl.css
  seedlet/style.css
Labels: [Status] Needs Review

#2507 Seedlet: Update the color annotations
  seedlet/inc/wpcom-colors.php
  seedlet/inc/wpcom-editor-colors.php
  seedlet/style.css
Labels: [Status] Needs Review

#2506 Fix/seedlet pattern placeholder images
  seedlet/assets/css/ie.css
  seedlet/assets/img/envelope.jpg
  seedlet/assets/img/plant_a.png
  seedlet/assets/img/plant_b.png
  seedlet/assets/img/plant_c.png
  seedlet/assets/sass/style.scss
  seedlet/inc/block-patterns.php
  seedlet/readme.txt
  seedlet/style-rtl.css
  seedlet/style.css
Labels: [Status] Needs Review

#2060 Photos: Fix invisible audio block
  photos/blocks.css
Labels: [Type] Bug
