Repository Automattic/themes, pull requests merged in 2020-11, with the labels that each got.

#2747 Spearhead: Add Global Styles CSS variables
  spearhead/variables.css
Labels: [Theme] Spearhead, [Type] Bug

#2734 Fix security issues
  alves/package-lock.json
  alves/package.json
  balasana/package-lock.json
  balasana/package.json
  barnsbury/package-lock.json
  barnsbury/package.json
  brompton/package-lock.json
  brompton/package.json
  calm-business/package-lock.json
  calm-business/package.json
  coutoire/package-lock.json
  coutoire/package.json
  dalston/package-lock.json
  elegant-business/package-lock.json
  elegant-business/package.json
Labels: [Status] Needs Review

#2756 Spearhead: fix custom colors
  seedlet/inc/wpcom-colors-utils.php
Labels: [Theme] Seedlet, [Theme] Spearhead

#1696 Ixion: Adjust version number
  ixion/readme.txt
Labels: [Status] Needs Review, [Status] Ready to Merge

#2494 remove the redundant if statement
  seedlet/template-parts/footer/footer-widgets.php
Labels: Involves Happiness, [Theme] Seedlet

#1814 Varia: Adjust bold formating (Maywood, Coutoire & Stow)
  coutoire/package.json
  coutoire/sass/_extra-child-theme.scss
  coutoire/sass/style-child-theme.scss
  coutoire/style-rtl.css
  coutoire/style.css
  maywood/package.json
  maywood/sass/_extra-child-theme.scss
  maywood/sass/style-child-theme-editor.scss
  maywood/sass/style-child-theme.scss
  maywood/style-editor.css
  maywood/style-rtl.css
  maywood/style.css
  stow/package.json
  stow/sass/_extra-child-theme.scss
  stow/sass/style-child-theme.scss
  stow/style-rtl.css
  stow/style.css
Labels: [Status] Needs Review

#2017 TextBook: Center image captions
  textbook/assets/css/blocks.css
Labels: [Status] Needs Review

#1666 Varia child themes: Adjust license information
  alves/sass/style-child-theme.scss
  balasana/sass/style-child-theme.scss
  barnsbury/sass/style-child-theme.scss
  brompton/sass/style-child-theme.scss
  coutoire/sass/style-child-theme.scss
  dalston/sass/style-child-theme.scss
  exford/sass/style-child-theme.scss
  hever/sass/style-child-theme.scss
  leven/sass/style-child-theme.scss
  mayland/sass/style-child-theme.scss
  maywood/sass/style-child-theme.scss
  morden/sass/style-child-theme.scss
  redhill/sass/style-child-theme.scss
  rivington/sass/style-child-theme.scss
  rockfield/sass/style-child-theme.scss
  shawburn/sass/style-child-theme.scss
  stow/sass/style-child-theme.scss
  stratford/sass/style-child-theme.scss
Labels: [Status] Ready to Merge

#1892 Alves: Remove top padding on mobile devices
  alves/sass/_extra-child-theme.scss
  alves/style-rtl.css
  alves/style.css
Labels: [Status] Needs Testing

#2762 Spearhead: add missing dotorg files + scripts
  README.md
  dotorg-exclude.txt
  package-dotorg.sh
  seedlet/package-dotorg.sh
  spearhead/LICENSE
  spearhead/readme.txt
Labels: [Theme] Spearhead

#2770 Varia-based themes: Reduce specificity on rules to hide extra color palettes
  alves/functions.php
  coutoire/functions.php
  dalston/functions.php
  exford/functions.php
  leven/functions.php
  mayland/functions.php
  maywood/functions.php
  redhill/functions.php
  rivington/functions.php
Labels: [Status] Needs Review, [Type] Bug

#2774 Seedlet Blocks: Remove extra group wrapper around template parts.
  seedlet-blocks/block-templates/index.html
  seedlet-blocks/block-templates/singular.html
  seedlet/assets/sass/blocks/utilities/_style.scss
  seedlet/style-rtl.css
  seedlet/style.css
  seedlet/style.css.map
Labels: [Type] Enhancement

#2773 Update the query loop for Seedlet blocks.
  seedlet-blocks/block-templates/index.html
Labels: [Theme] Seedlet Blocks

#1686 Lodestar: Fix image block background color issue
  lodestar/style.css
Labels: [Status] Needs Theam Reply

#2304 #2059 - Pique: Blocks with Wide Alignment Displayed Incorrectly When Nested Inside Block with Full Alignment
  pique/assets/css/blocks.css
  pique/style.css
Labels: [Status] Needs Review, [Status] Needs Testing

#2302 Brompton: Bottom of Site Header is Covered When Cover Block has Transparency Effect Applied
  brompton/sass/_extra-child-theme.scss
  brompton/style-rtl.css
  brompton/style.css
Labels: [Status] Needs Review, [Status] Needs Testing

#2782 Varia/Alves/Hever/Morden align site logo with the menu
  alves/sass/_extra-child-theme.scss
  alves/style-rtl.css
  alves/style.css
  hever/sass/_extra-child-theme.scss
  hever/style-rtl.css
  hever/style.css
  morden/header.php
  morden/sass/_extra-child-theme.scss
  morden/style-rtl.css
  morden/style.css
  varia/header.php
  varia/inc/wpcom.php
Labels: [Status] Needs Review, [Theme] Varia

#2798 Morden and Varia: fixed conditional class not working corectly
  morden/header.php
  morden/package-lock.json
  morden/package.json
  morden/sass/style-child-theme.scss
  morden/style-rtl.css
  morden/style.css
  varia/header.php
  varia/package-lock.json
  varia/package.json
  varia/style-rtl.css
  varia/style.css
  varia/style.scss
Labels: Involves Happiness, [Theme] Varia, [Type] Bug

#2799 Morden, Varia: changed default value for get_theme_mod
  morden/header.php
  morden/package-lock.json
  morden/package.json
  morden/sass/style-child-theme.scss
  morden/style-rtl.css
  morden/style.css
  varia/header.php
  varia/package-lock.json
  varia/package.json
  varia/style-rtl.css
  varia/style.css
  varia/style.scss
Labels: [Theme] Varia, [Type] Bug

#2807 fixed z-index of header semicircle
  brompton/package-lock.json
  brompton/package.json
  brompton/sass/_extra-child-theme.scss
  brompton/sass/style-child-theme.scss
  brompton/style-rtl.css
  brompton/style.css
Labels: Involves Happiness, [Type] Bug

#2816 Brompton: fixed header when changing color palette
  brompton/inc/wpcom-colors.php
  brompton/package-lock.json
  brompton/package.json
  brompton/sass/style-child-theme.scss
  brompton/style-rtl.css
  brompton/style.css
Labels: [Type] Bug

#2331 Button 2: More Block padding
  button-2/style.css
Labels: [Status] Needs Review

#2763 Seedlet/Spearhead: Fix mobile heading word-breaks and spacing rules in Jetpack layout block.
  seedlet/assets/css/style-editor.css
  seedlet/assets/sass/vendors/jetpack/blocks/layout-grid/_config.scss
  seedlet/assets/sass/vendors/jetpack/blocks/layout-grid/_style.scss
  seedlet/style-rtl.css
  seedlet/style.css
Labels: [Status] Needs Review, [Theme] Seedlet, [Theme] Spearhead

#2366 Seedlet: support filtering archive page titles
  seedlet/archive.php
  seedlet/assets/sass/style.scss
  seedlet/functions.php
  seedlet/inc/template-functions.php
  seedlet/style-rtl.css
  seedlet/style.css
Labels: [Theme] Seedlet

#2779 Spearhead: fix dotorg submission issues
  package-dotorg.sh
  spearhead/assets/sass/style.scss
  spearhead/style-rtl.css
  spearhead/style.css
  spearhead/style.css.map
Labels: [Theme] Spearhead

#872 AltoFocus: Allow widgets to be shown on the homepage
  altofocus/index.php
  altofocus/page.php
  altofocus/style.css
Labels: [Type] Enhancement

#2850 Barnsbury: updated position of logo when no tagline or title are enabled
  barnsbury/package-lock.json
  barnsbury/package.json
  barnsbury/sass/_extra-child-theme.scss
  barnsbury/sass/style-child-theme.scss
  barnsbury/style-rtl.css
  barnsbury/style.css
Labels: [Status] Needs Review, [Theme] Varia

#2858 Require theme files without assuming the theme is installed
  spearhead/inc/wpcom-colors.php
Labels: [Theme] Spearhead

#2841 Seedlet: Remove side padding from Group block
  altofocus/index.php
  altofocus/page.php
  seedlet/assets/sass/blocks/group/_style.scss
  seedlet/assets/sass/style.scss
  seedlet/inc/template-functions.php
  seedlet/package.json
  seedlet/style-rtl.css
  seedlet/style.css
Labels: Involves Happiness, [Status] Needs Review, [Type] Bug

#2843 Varia: use the_content() for Testimonials archives
  varia/archive-jetpack-testimonial.php
  varia/template-parts/content/content-testimonial-excerpt.php
Labels: [Status] Needs Review

#2865 fix spearhead fatal
  seedlet/inc/wpcom-colors.php
  spearhead/inc/wpcom-colors-utils.php
  spearhead/inc/wpcom-colors.php
Labels: [Theme] Spearhead
