Repository Automattic/themes, pull requests merged in 2023-10, with the labels that each got.

#7373 Update styles of question feedback
  course/styles/blue.json
  course/styles/dark.json
  course/styles/gold.json
  course/theme.json
Labels: [Project] Frontend Improvements

#7408 Add theme: Programme by @henriqueiamarino
  programme/assets/fonts/evolventa_normal_700.woff
  programme/assets/fonts/inter_normal_400.ttf
  programme/assets/fonts/inter_normal_600.ttf
  programme/assets/fonts/inter_normal_700.ttf
  programme/assets/fonts/libre-baskerville_italic_400.ttf
  programme/assets/fonts/libre-baskerville_normal_400.ttf
  programme/functions.php
  programme/parts/footer-minimal.html
  programme/parts/footer.html
  programme/parts/header-minimal.html
  programme/parts/header.html
  programme/parts/post-meta.html
  programme/patterns/404.php
  programme/patterns/big-header.php
  programme/patterns/comments.php
  programme/patterns/footer.php
  programme/patterns/hidden-no-results-content.php
  programme/patterns/search.php
  programme/readme.txt
  programme/screenshot.png
  programme/style.css
  programme/styles/century.json
  programme/styles/futura.json
  programme/templates/404.html
  programme/templates/archive.html
  programme/templates/home.html
  programme/templates/index.html
  programme/templates/page.html
  programme/templates/search.html
  programme/templates/single.html
  programme/theme.json
Labels: Themes

#7418 Barnsbury23: Remove all wp-image class names
  barnsbury23/patterns/front-page.php
  barnsbury23/patterns/hero-green.php
  barnsbury23/patterns/home-clean.php
  barnsbury23/patterns/home.php
  barnsbury23/patterns/numbers-clean.php
  barnsbury23/patterns/numbers-green.php
  barnsbury23/patterns/post-meta.php
  barnsbury23/patterns/testimonials-alt.php
  barnsbury23/patterns/testimonials.php
  barnsbury23/theme.json
Labels: [Theme] Barnsbury23

#7427 Sensei frontend style improvements
  course/readme.txt
  course/style.css
  course/styles/blue.json
  course/styles/dark.json
  course/styles/gold.json
  course/theme.json
Labels: [Project] Frontend Improvements
