Repository Automattic/themes, pull requests merged in 2023-12, with the labels that each got.

#7518 Varia: Include Jetpack Content Options
  varia/functions.php
  varia/template-parts/content/content-page.php
Labels: OSS Citizen, Customer Report

#7534 Add strict types declaration to latest themes
  beep/functions.php
  ici/functions.php
  indice/functions.php
  spiel/functions.php
  xanadu/functions.php
Labels: [Type] Bug

#7575 Block Canvas: Update header alignment
  block-canvas/parts/header.html
Labels: [Theme] Block Canvas
