Repository Automattic/themes, pull requests merged in 2023-09, with the labels that each got.

#7342 Fix navigation blocks - Remove ref attribute to avoid error message
  awburn/parts/header.html
  awburn/patterns/footer-home.php
  awburn/patterns/footer.php
  bibliophile/parts/header.html
  calyx/parts/header.html
  common/parts/header.html
  cortado/parts/header-inverted.html
  cortado/parts/header.html
  covr/parts/header.html
  ctlg/templates/page.html
  ctlg/templates/single.html
  erma/parts/header.html
  fewer/parts/header.html
  jaida/parts/header.html
  jaida/parts/secondary-header.html
  organizer/parts/header.html
  pieria/templates/404.html
  pieria/templates/archive.html
  pieria/templates/index.html
  pieria/templates/page.html
  pieria/templates/search.html
  pieria/templates/single.html
  poesis/patterns/header.php
  ron/templates/archive.html
  ron/templates/page.html
  ron/templates/search.html
  ron/templates/single.html
  sten/parts/header.html
  ueno/parts/header.html
Labels: Lego Maintenance

#7317 Quiz footer button styles fix
  course/styles/blue.json
  course/styles/dark.json
  course/styles/gold.json
  course/theme.json
Labels: [Project] Frontend Improvements

#7349 Meraki - Fix query block error in search template
  meraki/templates/search.html
Labels: Lego Maintenance

#7350 Blockbase - Fix query block error in search template
  blockbase/templates/search.html
Labels: Lego Maintenance

#7331 Update stylings for quiz, questions and answers
  course/styles/blue.json
  course/styles/dark.json
  course/styles/gold.json
  course/theme.json
Labels: [Project] Frontend Improvements

#7352 Awburn: fix home template blocks
  awburn/patterns/home.php
  awburn/patterns/page-home.php
Labels: [Theme] Shawburn

#7354 Remove category from taxQuery to avoid a not found error
  barnsbury23/patterns/front-page.php
  barnsbury23/patterns/home-alt.php
  barnsbury23/patterns/home.php
  barnsbury23/templates/index.html
  curriculum/patterns/page-home-alt.php
  curriculum/templates/home.html
  grammerone/templates/index.html
  raw/patterns/home.php
  texty/parts/sidebar.html
Labels: Lego Maintenance

#7351 Remove Rubik from Ueno and Dawson
  dawson/theme.json
  ueno/theme.json
Labels: [Theme] Ueno

#7324 Course Theme: Frontend improvements feature branch PR
  course/styles/blue.json
  course/styles/dark.json
  course/styles/gold.json
  course/theme.json
Labels: [Project] Frontend Improvements
