Repository Automattic/themes, pull requests merged in 2023-11, with the labels that each got.

#7308 Eventual: Add theme
  eventual/assets/fonts/barlow-condensed_italic_600.ttf
  eventual/assets/fonts/barlow-condensed_normal_600.ttf
  eventual/assets/fonts/figtree_italic_400.ttf
  eventual/assets/fonts/figtree_italic_700.ttf
  eventual/assets/fonts/figtree_normal_400.ttf
  eventual/assets/fonts/figtree_normal_700.ttf
  eventual/assets/images/image-from-rawpixel-id-3306149_distorted.jpg
  eventual/assets/images/image-from-rawpixel-id-5922463_distorted.jpg
  eventual/functions.php
  eventual/parts/footer-light.html
  eventual/parts/footer.html
  eventual/parts/header.html
  eventual/parts/post-meta.html
  eventual/patterns/404.php
  eventual/patterns/comments.php
  eventual/patterns/footer-light.php
  eventual/patterns/footer.php
  eventual/patterns/hidden-no-results-content.php
  eventual/patterns/home.php
  eventual/patterns/index.php
  eventual/readme.txt
  eventual/screenshot.png
  eventual/style.css
  eventual/templates/404.html
  eventual/templates/archive.html
  eventual/templates/home.html
  eventual/templates/index.html
  eventual/templates/page.html
  eventual/templates/search.html
  eventual/templates/single.html
  eventual/theme.json
Labels: [Theme] Eventual

#7479 Multiple Block Themes: Fix Cursor When Hovering Links
  artly/styles/space-cadet.json
  covr/theme.json
  didone/theme.json
  foam/theme.json
  loic/theme.json
  mpho/theme.json
  poesis/theme.json
  strand/theme.json
  sunderland/theme.json
Labels: OSS Citizen

#7480 Programme: Fix Century & Futury Style Colours
  programme/styles/century.json
  programme/styles/futura.json
  programme/templates/archive.html
  programme/templates/home.html
  programme/theme.json
Labels: OSS Citizen

#7478 Varia/Seedlet: Sync with Jetpack Social Menu
  seedlet/classes/class-seedlet-svg-icons.php
  varia/classes/class-varia-svg-icons.php
Labels: OSS Citizen

#7502 Messagerie: update variations
  messagerie/theme.json
Labels: [Theme] Messagerie
