Repository Automattic/themes, pull requests merged in 2024-06, with the labels that each got.

#7849 Spearhead: remove excess JS from the frontend
  spearhead/functions.php
Labels: [Type] Bug, [Theme] Spearhead

#7853 Spearhead: fix wp editor colors import path
  spearhead/inc/wpcom-editor-colors.php
Labels: [Type] Bug

#7809 Otis: Update theme and prepare for Dotorg submission
  otis/parts/header-2.html
  otis/parts/header.html
  otis/readme.txt
  otis/style.css
  otis/templates/home.html
  otis/templates/index.html
  otis/templates/page.html
  otis/templates/single.html
  otis/theme.json
Labels: OSS Citizen
