Repository Automattic/themes, pull requests merged in 2024-08, with the labels that each got.

#7960 Cottage: add theme
  cottage/assets/fonts/cormorant_italic_300.ttf
  cottage/assets/fonts/cormorant_italic_400.ttf
  cottage/assets/fonts/cormorant_italic_500.ttf
  cottage/assets/fonts/cormorant_italic_600.ttf
  cottage/assets/fonts/cormorant_italic_700.ttf
  cottage/assets/fonts/cormorant_normal_300.ttf
  cottage/assets/fonts/cormorant_normal_400.ttf
  cottage/assets/fonts/cormorant_normal_500.ttf
  cottage/assets/fonts/cormorant_normal_600.ttf
  cottage/assets/fonts/cormorant_normal_700.ttf
  cottage/assets/fonts/league-spartan_normal_300.ttf
  cottage/assets/fonts/league-spartan_normal_400.ttf
  cottage/assets/fonts/league-spartan_normal_500.ttf
  cottage/assets/fonts/league-spartan_normal_600.ttf
  cottage/assets/fonts/league-spartan_normal_700.ttf
  cottage/assets/fonts/sorts-mill-goudy_italic_400.ttf
  cottage/assets/fonts/sorts-mill-goudy_normal_400.ttf
  cottage/assets/images/cottage_background-scaled.jpg
  cottage/assets/images/cottage_post_1-min.jpg
  cottage/assets/images/mood_1-min.jpg
  cottage/assets/images/mood_2-min.jpg
  cottage/assets/images/mood_3-min.jpg
  cottage/assets/images/mood_4-min.jpg
  cottage/assets/images/mood_5-min.jpg
  cottage/assets/images/mood_6-min.jpg
  cottage/assets/images/mood_7-scaled.jpg
  cottage/assets/images/mood_8-min.jpg
  cottage/functions.php
  cottage/parts/comments.html
  cottage/parts/footer.html
  cottage/parts/header-with-cover.html
  cottage/parts/header-with-sticky-post.html
  cottage/parts/header.html
  cottage/patterns/404.php
  cottage/patterns/archive.php
  cottage/patterns/footer.php
  cottage/patterns/front-page.php
  cottage/patterns/header-with-cover.php
  cottage/patterns/header-with-sticky-post.php
  cottage/patterns/header.php
  cottage/patterns/index.php
  cottage/patterns/latest-post-heading.php
  cottage/patterns/no-results-content.php
  cottage/patterns/page.php
  cottage/patterns/post-author.php
  cottage/patterns/post-list.php
  cottage/patterns/search.php
  cottage/patterns/single.php
  cottage/readme.txt
  cottage/screenshot.png
  cottage/style.css
  cottage/templates/404.html
  cottage/templates/archive.html
  cottage/templates/front-page.html
  cottage/templates/index.html
  cottage/templates/page.html
  cottage/templates/search.html
  cottage/templates/single.html
  cottage/theme.json
Labels: OSS Citizen

#7971 Goodskin: add theme
  goodskin/assets/fonts/.DS_Store
  goodskin/assets/fonts/Archivo-Italic-VariableFont_wdth,wght.ttf
  goodskin/assets/fonts/Archivo-VariableFont_wdth,wght.ttf
  goodskin/assets/fonts/InstrumentSerif-Italic.ttf
  goodskin/assets/fonts/InstrumentSerif-Regular.ttf
  goodskin/assets/fonts/cormorant-garamond_italic_300.ttf
  goodskin/assets/fonts/cormorant-garamond_italic_400.ttf
  goodskin/assets/fonts/cormorant-garamond_italic_500.ttf
  goodskin/assets/fonts/cormorant-garamond_italic_600.ttf
  goodskin/assets/fonts/cormorant-garamond_italic_700.ttf
  goodskin/assets/fonts/cormorant-garamond_normal_300.ttf
  goodskin/assets/fonts/cormorant-garamond_normal_400.ttf
  goodskin/assets/fonts/cormorant-garamond_normal_500.ttf
  goodskin/assets/fonts/cormorant-garamond_normal_600.ttf
  goodskin/assets/fonts/cormorant-garamond_normal_700.ttf
  goodskin/assets/images/.DS_Store
  goodskin/assets/images/skin-blog-about-image-792x1024.jpg
  goodskin/assets/images/skin-blog-home-image-2-2.jpg
  goodskin/assets/images/skin-blog-home-image-3-1.jpg
  goodskin/assets/images/skin-blog-product-1-1.jpg
  goodskin/assets/images/skin-blog-product-2-1.jpg
  goodskin/assets/images/skin-blog-product-3-1.jpg
  goodskin/assets/images/skin-blog-product-4-1-1024x1024.jpg
  goodskin/functions.php
  goodskin/parts/comments.html
  goodskin/parts/footer.html
  goodskin/parts/header.html
  goodskin/parts/sidebar.html
  goodskin/patterns/404.php
  goodskin/patterns/about-page-heading-paragraph-image.php
  goodskin/patterns/footer.php
  goodskin/patterns/home.php
  goodskin/patterns/no-results-content.php
  goodskin/patterns/product-ratings-row.php
  goodskin/patterns/search.php
  goodskin/patterns/single.php
  goodskin/patterns/two-column-gallery.php
  goodskin/readme.txt
  goodskin/screenshot.png
  goodskin/style.css
  goodskin/styles/blush.json
  goodskin/styles/eyeshadow.json
  goodskin/styles/jojoba.json
  goodskin/templates/404.html
  goodskin/templates/archive.html
  goodskin/templates/home.html
  goodskin/templates/index.html
  goodskin/templates/page.html
  goodskin/templates/search.html
  goodskin/templates/single.html
  goodskin/templates/wp-custom-template-page-no-title.html
  goodskin/theme.json
Labels: OSS Citizen

#7989 Minor style tweaks for Assembler
  assembler/style.css
  assembler/theme.json
Labels: [Type] Bug, [Theme] Assembler

#7961 Saison: add theme
  saison/assets/fonts/eb-garamond_italic_400.ttf
  saison/assets/fonts/eb-garamond_italic_700.ttf
  saison/assets/fonts/eb-garamond_normal_400.ttf
  saison/assets/fonts/eb-garamond_normal_700.ttf
  saison/assets/fonts/fraunces_italic_100.ttf
  saison/assets/fonts/plus-jakarta-sans_italic_300.ttf
  saison/assets/fonts/plus-jakarta-sans_italic_400.ttf
  saison/assets/fonts/plus-jakarta-sans_italic_500.ttf
  saison/assets/fonts/plus-jakarta-sans_italic_600.ttf
  saison/assets/fonts/plus-jakarta-sans_italic_700.ttf
  saison/assets/fonts/plus-jakarta-sans_normal_300.ttf
  saison/assets/fonts/plus-jakarta-sans_normal_400.ttf
  saison/assets/fonts/plus-jakarta-sans_normal_500.ttf
  saison/assets/fonts/plus-jakarta-sans_normal_600.ttf
  saison/assets/fonts/plus-jakarta-sans_normal_700.ttf
  saison/assets/fonts/sora_normal_400.ttf
  saison/assets/fonts/sora_normal_700.ttf
  saison/assets/fonts/unbounded_normal_500.ttf
  saison/assets/images/home-image-1-scaled.jpg
  saison/assets/images/home-image-1.jpg
  saison/assets/images/home-image-2-1024x556.jpg
  saison/assets/images/home-image-2.jpg
  saison/assets/images/home-image-3-1024x891.jpg
  saison/assets/images/home-image-3.jpg
  saison/assets/images/pattern-image-1.jpg
  saison/assets/images/pattern-image-2.jpg
  saison/assets/images/pattern-image-3.jpg
  saison/functions.php
  saison/parts/footer.html
  saison/parts/header.html
  saison/parts/post-meta.html
  saison/patterns/404.php
  saison/patterns/comments.php
  saison/patterns/footer.php
  saison/patterns/hidden-no-results-content.php
  saison/patterns/home.php
  saison/patterns/homepage.php
  saison/patterns/landing-cover-image.php
  saison/patterns/landing-image-on-the-left.php
  saison/patterns/landing-image-on-the-right.php
  saison/patterns/location.php
  saison/patterns/menu.php
  saison/readme.txt
  saison/screenshot.png
  saison/style.css
  saison/styles/kale.json
  saison/styles/lemon-pie.json
  saison/styles/white-rice.json
  saison/templates/404.html
  saison/templates/archive.html
  saison/templates/home.html
  saison/templates/index.html
  saison/templates/page.html
  saison/templates/search.html
  saison/templates/single.html
  saison/templates/wp-custom-template-page-no-title.html
  saison/theme.json
Labels: OSS Citizen

#8011 Theme preview: use pull_request_target
  .github/workflows/preview-theme.yml
Labels: [Type] Bug

#8019 Tweak rootHasVersionBump logic
  theme-utils.mjs
Labels: Tools

#8020 Fix dotorg deploy script
  deploy-dotorg.sh
Labels: Tools

#8026 Brat: add theme (Rename to Partygurl)
  .gitignore
  brat/assets/fonts/texgyreheroscn-bold.otf
  brat/assets/fonts/texgyreheroscn-bolditalic.otf
  brat/assets/fonts/texgyreheroscn-italic.otf
  brat/assets/fonts/texgyreheroscn-regular.otf
  brat/functions.php
  brat/parts/footer.html
  brat/parts/header.html
  brat/parts/post-meta.html
  brat/patterns/404.php
  brat/patterns/footer.php
  brat/patterns/hidden-no-results-content.php
  brat/patterns/post-meta.php
  brat/readme.txt
  brat/screenshot.png
  brat/style.css
  brat/templates/404.html
  brat/templates/archive.html
  brat/templates/index.html
  brat/templates/page.html
  brat/templates/search.html
  brat/templates/single.html
  brat/theme.json
  goodskin/assets/fonts/.DS_Store
  goodskin/assets/images/.DS_Store
Labels: OSS Citizen

#7515 Independent Publisher 2: Fix Gravatar Not Appearing
  independent-publisher-2/inc/extras.php
Labels: OSS Citizen

#8045 Update Node/npm and dependencies
  .husky/pre-commit
  .nvmrc
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: dependencies

#8039 Add automated JSON schema validation
  .github/workflows/validate-theme.yml
  CONTRIBUTING.md
  package-lock.json
  package.json
  theme-utils.mjs
Labels: Automation
