Repository Automattic/themes, pull requests merged in 2024-12, with the labels that each got.

#8489 Fix Assembler outline variation size and style
  assembler/style.css
  assembler/theme.json
Labels: [Type] Bug

#8490 Remove forced post title font size for Assembler
  assembler/templates/template-page-w-title.html
  assembler/theme.json
Labels: [Type] Bug

#8491 Add blank template to Assembler
  assembler/templates/template-blank.html
Labels: [Type] Enhancement, [Theme] Assembler

#8469 Rockfield: Fix cart button styles
  rockfield/sass/style-child-theme-woocommerce.scss
  rockfield/style-rtl.css
  rockfield/style-woocommerce-rtl.css
  rockfield/style-woocommerce.css
  rockfield/style.css
Labels: Groundskeeping

#8480 Dadaist: add theme
  dadaist/assets/fonts/antique-serie/antique-serie-400-normal.woff2
  dadaist/assets/fonts/besley/besley-400-italic.ttf
  dadaist/assets/fonts/besley/besley-400-normal.ttf
  dadaist/assets/fonts/besley/besley-700-italic.ttf
  dadaist/assets/fonts/besley/besley-700-normal.ttf
  dadaist/assets/fonts/futura-renner/futura-renner-300-normal.woff2
  dadaist/assets/fonts/futura-renner/futura-renner-400-normal.woff2
  dadaist/assets/fonts/gravepresse/gravepresse-700-normal.woff2
  dadaist/assets/fonts/inter/inter-300-italic.woff2
  dadaist/assets/fonts/inter/inter-300-normal.woff2
  dadaist/assets/fonts/inter/inter-400-italic.woff2
  dadaist/assets/fonts/inter/inter-400-normal.woff2
  dadaist/assets/fonts/inter/inter-500-italic.woff2
  dadaist/assets/fonts/inter/inter-500-normal.woff2
  dadaist/assets/fonts/inter/inter-600-italic.woff2
  dadaist/assets/fonts/inter/inter-600-normal.woff2
  dadaist/assets/fonts/overused-grotesk/overused-grotesk-400-italic.woff2
  dadaist/assets/fonts/overused-grotesk/overused-grotesk-400-normal.woff2
  dadaist/assets/fonts/overused-grotesk/overused-grotesk-600-italic.woff2
  dadaist/assets/fonts/overused-grotesk/overused-grotesk-600-normal.woff2
  dadaist/assets/fonts/overused-grotesk/overused-grotesk-700-italic.woff2
  dadaist/assets/fonts/overused-grotesk/overused-grotesk-700-normal.woff2
  dadaist/assets/fonts/urw-gothic/urw-gothic-400-italic.ttf
  dadaist/assets/fonts/urw-gothic/urw-gothic-400-normal.ttf
  dadaist/assets/fonts/urw-gothic/urw-gothic-700-italic.otf
  dadaist/assets/fonts/urw-gothic/urw-gothic-700-normal.ttf
  dadaist/assets/images/dada_collage-bg.png
  dadaist/assets/images/dada_haltfone-tex_1.png
  dadaist/assets/images/dada_haltfone-tex_2.png
  dadaist/assets/images/dada_img_eye.png
  dadaist/assets/images/dada_img_mouth.png
  dadaist/functions.php
  dadaist/parts/comments.html
  dadaist/parts/footer.html
  dadaist/parts/header.html
  dadaist/parts/post-meta.html
  dadaist/patterns/404.php
  dadaist/patterns/archive.php
  dadaist/patterns/footer.php
  dadaist/patterns/header.php
  dadaist/patterns/home.php
  dadaist/patterns/index.php
  dadaist/patterns/page.php
  dadaist/patterns/post-meta.php
  dadaist/patterns/search.php
  dadaist/patterns/single.php
  dadaist/readme.txt
  dadaist/screenshot.png
  dadaist/style.css
  dadaist/styles/eroded-styles.json
  dadaist/styles/expanded-type.json
  dadaist/styles/geometric-headliner.json
  dadaist/templates/404.html
  dadaist/templates/archive.html
  dadaist/templates/home.html
  dadaist/templates/index.html
  dadaist/templates/page.html
  dadaist/templates/search.html
  dadaist/templates/single.html
  dadaist/theme.json
Labels: Ready to launch

#8513 Psychedeli: add theme
  psychedeli/assets/fonts/apfel-grotezk/apfel-grotezk_normal_400.otf
  psychedeli/assets/fonts/apfel-grotezk/apfel-grotezk_normal_700.otf
  psychedeli/assets/fonts/bricolage-grotesque/bricolage-grotesque-400-normal.woff2
  psychedeli/assets/fonts/bricolage-grotesque/bricolage-grotesque-700-normal.woff2
  psychedeli/assets/fonts/dodgy-ultra/dodgy-ultra-700-normal.ttf
  psychedeli/assets/fonts/lobular/lobular-400-normal.woff2
  psychedeli/assets/fonts/psychedelic-cowboy/psychedelic-cowboy-700-normal.otf
  psychedeli/assets/images/Aldous_Huxley.jpg
  psychedeli/assets/images/Carlos-Castaneda.jpg
  psychedeli/assets/images/Hermann-Hesse-1.jpg
  psychedeli/assets/images/Hunter-Thompson.jpg
  psychedeli/assets/images/psychedeli_flowerpower.png
  psychedeli/functions.php
  psychedeli/parts/comments.html
  psychedeli/parts/footer.html
  psychedeli/parts/header-home.html
  psychedeli/parts/header.html
  psychedeli/parts/post-meta.html
  psychedeli/patterns/404.php
  psychedeli/patterns/archive.php
  psychedeli/patterns/footer.php
  psychedeli/patterns/header-home.php
  psychedeli/patterns/header.php
  psychedeli/patterns/home.php
  psychedeli/patterns/index.php
  psychedeli/patterns/search.php
  psychedeli/patterns/single.php
  psychedeli/readme.txt
  psychedeli/screenshot.png
  psychedeli/style.css
  psychedeli/styles/green-dandelion.json
  psychedeli/styles/pink-acqua.json
  psychedeli/styles/shady-silver.json
  psychedeli/styles/turquoise-cream.json
  psychedeli/templates/404.html
  psychedeli/templates/archive.html
  psychedeli/templates/home.html
  psychedeli/templates/index.html
  psychedeli/templates/page.html
  psychedeli/templates/search.html
  psychedeli/templates/single.html
  psychedeli/theme.json
Labels: Ready to launch

#8540 Fix checkThemeForVersionBump value
  theme-utils.mjs
Labels: Tools

#8544 Tools: Add separate version bump script for GH actions
  .github/workflows/version-bump.yml
  package.json
  theme-utils.mjs
Labels: Tools
