Repository Automattic/themes, pull requests merged in 2024-01, with the labels that each got.

#7583 Minor tweaks for Assembler
  assembler/style.css
  assembler/templates/page.html
  assembler/theme.json
Labels: [Type] Enhancement

#7565 Update theme erma
  erma/parts/footer.html
  erma/parts/header.html
  erma/templates/404.html
  erma/templates/archive.html
  erma/templates/center-aligned-post.html
  erma/templates/home.html
  erma/templates/index.html
  erma/templates/page.html
  erma/templates/search.html
  erma/templates/single.html
  erma/theme.json
Labels: OSS Citizen

#7563 Update theme ron
  ron/parts/header.html
  ron/templates/404.html
  ron/templates/archive.html
  ron/templates/page.html
  ron/templates/search.html
  ron/templates/single.html
  ron/theme.json
Labels: OSS Citizen

#7481 Dara: Fix TikTok Embed Block
  dara/blocks.css
Labels: [Type] Enhancement, [Theme] Dara, OSS Citizen

#7617 Assembler: Fonts, text balance, field styling
  assembler/assets/fonts/fahkwang/Fahkwang-Bold.ttf
  assembler/assets/fonts/fahkwang/Fahkwang-BoldItalic.ttf
  assembler/assets/fonts/fahkwang/Fahkwang-Italic.ttf
  assembler/assets/fonts/fahkwang/Fahkwang-Regular.ttf
  assembler/assets/fonts/fahkwang/OFL.txt
  assembler/assets/fonts/roboto/LICENSE.txt
  assembler/assets/fonts/roboto/Roboto-Bold.ttf
  assembler/assets/fonts/roboto/Roboto-BoldItalic.ttf
  assembler/assets/fonts/roboto/Roboto-Italic.ttf
  assembler/assets/fonts/roboto/Roboto-Light.ttf
  assembler/assets/fonts/roboto/Roboto-LightItalic.ttf
  assembler/assets/fonts/roboto/Roboto-Regular.ttf
  assembler/screenshot.png
  assembler/style.css
  assembler/theme.json
Labels: [Type] Enhancement

#7629 Assembler: Remove Instrument serif bold variant from theme.json
  assembler/theme.json
Labels: [Type] Bug

#7631 Multiple Themes: Fix broken template previews due to site specific attributes in template/pattern markup
  allez/patterns/header-with-sticky-post.php
  blogorama/patterns/header-pages.php
  blogorama/patterns/page.php
  cortado/templates/page.html
  cortado/templates/single.html
  craftfully/patterns/footer.php
  eventual/patterns/home.php
  eventual/patterns/index.php
  eventual/templates/archive.html
  eventual/templates/index.html
  eventual/templates/search.html
  lois/patterns/post-list.php
  messagerie/patterns/archive.php
  messagerie/patterns/home.php
  messagerie/patterns/index.php
  messagerie/patterns/search.php
  ritratto/patterns/right-sidebar.php
  stage/patterns/header.php
  stage/patterns/right-sidebar.php
  stage/templates/archive.html
  stage/templates/index.html
  stage/templates/search.html
  sunderland/parts/header.html
Labels: Lego Maintenance
