Repository Automattic/themes, pull requests merged in 2024-03, with the labels that each got.

#7670 Lettre: Navigation styling fixes
  lettre/style.css
Labels: [Theme] Lettre

#7501 Stage: update style variations
  stage/theme.json
Labels: [Theme] Stage

#7462 Fix extra padding issue in outline buttons
  course/assets/css/default.css
  course/assets/css/gold.css
Labels: [Project] Frontend Improvements

#7465 Make theme variation body class available in editor screens
  course/functions.php
Labels: [Project] Frontend Improvements

#7694 Deploy script: Improve npm versioning step
  theme-utils.mjs
Labels: Tools

#7686 Assembler: Lint styles
  assembler/style.css
Labels: [Theme] Assembler

#7702 Update theme fewer
  fewer/parts/footer.html
  fewer/readme.txt
  fewer/screenshot.png
  fewer/style.css
Labels: OSS Citizen

#7703 Common: Preps for submission
  common/style.css
  common/theme.json
Labels: OSS Citizen
