Repository Automattic/themes, pull requests merged in 2024-09, with the labels that each got.

#7917 The Shore: add theme
  the-shore/assets/fonts/rnCr-xNNww_2s0amA-M7mHnOSOuk.woff2
  the-shore/assets/fonts/rnCs-xNNww_2s0amA9uCt13DY_etWWIJ.woff2
  the-shore/assets/fonts/rnCs-xNNww_2s0amA9uSsF3DY_etWWIJ.woff2
  the-shore/assets/fonts/rnCs-xNNww_2s0amA9v2s13DY_etWWIJ.woff2
  the-shore/assets/fonts/rnCs-xNNww_2s0amA9vKsV3DY_etWWIJ.woff2
  the-shore/assets/fonts/rnCs-xNNww_2s0amA9vmtl3DY_etWWIJ.woff2
  the-shore/assets/fonts/rnCt-xNNww_2s0amA9M8knjsTfukQHs.woff2
  the-shore/assets/fonts/rnCu-xNNww_2s0amA9M8qonFafaPXHIJErY.woff2
  the-shore/assets/fonts/rnCu-xNNww_2s0amA9M8qqXCafaPXHIJErY.woff2
  the-shore/assets/fonts/rnCu-xNNww_2s0amA9M8qrXHafaPXHIJErY.woff2
  the-shore/assets/fonts/rnCu-xNNww_2s0amA9M8qsHDafaPXHIJErY.woff2
  the-shore/assets/fonts/rnCu-xNNww_2s0amA9M8qtHEafaPXHIJErY.woff2
  the-shore/assets/fonts/tDaH2o2WnlgI0FNDgduEk4jAhwgumbU1SVfU5BD8OuRL8OstC6KOhgvBYWSFJ-Mgdrgiju6fF8meZm0rk4eF-ZugTJ1dGPK7Fu0jUdk.woff2
  the-shore/assets/fonts/tDaH2o2WnlgI0FNDgduEk4jAhwgumbU1SVfU5BD8OuRL8OstC6KOhgvBYWSFJ-Mgdrgiju6fF8meZm0rk4eF-ZugTMNdGPK7Fu0jUdk.woff2
  the-shore/assets/fonts/tDaH2o2WnlgI0FNDgduEk4jAhwgumbU1SVfU5BD8OuRL8OstC6KOhgvBYWSFJ-Mgdrgiju6fF8meZm0rk4eF-ZugTPFdGPK7Fu0jUdk.woff2
  the-shore/assets/images/hotel_cover_image.jpg
  the-shore/assets/images/hotel_image_10.jpg
  the-shore/assets/images/hotel_image_11.jpg
  the-shore/assets/images/hotel_image_12.jpg
  the-shore/assets/images/hotel_image_2.jpg
  the-shore/assets/images/hotel_image_3.jpg
  the-shore/assets/images/hotel_image_4.jpg
  the-shore/assets/images/hotel_image_5.jpg
  the-shore/assets/images/hotel_image_6.jpg
  the-shore/assets/images/hotel_image_7.jpg
  the-shore/assets/images/hotel_image_8.jpg
  the-shore/assets/images/hotel_image_9.jpg
  the-shore/assets/images/hotel_logo_2.png
  the-shore/assets/images/line-1.png
  the-shore/assets/images/line_light.png
  the-shore/functions.php
  the-shore/parts/footer.html
  the-shore/parts/header-homepage.html
  the-shore/parts/header.html
  the-shore/parts/post-meta.html
  the-shore/patterns/archive.php
  the-shore/patterns/header-homepage.php
  the-shore/patterns/home.php
  the-shore/patterns/index.php
  the-shore/patterns/search.php
  the-shore/readme.txt
  the-shore/screenshot.png
  the-shore/style.css
  the-shore/styles/clay-mask.json
  the-shore/styles/deep-sea.json
  the-shore/styles/pristine-white.json
  the-shore/templates/404.html
  the-shore/templates/archive.html
  the-shore/templates/home.html
  the-shore/templates/index.html
  the-shore/templates/page.html
  the-shore/templates/search.html
  the-shore/templates/single.html
  the-shore/templates/wp-custom-template-page-no-title.html
  the-shore/theme.json
Labels: OSS Citizen

#7953 Update theme jaida
  jaida/patterns/404.php
  jaida/patterns/footer.php
  jaida/playground.zip
  jaida/templates/404.html
  jaida/templates/archive.html
  jaida/templates/index.html
  jaida/templates/search.html
  jaida/theme.json
Labels: OSS Citizen

#7955 Sprinkler: add theme
  sprinkler/assets/fonts/lato_italic_300.ttf
  sprinkler/assets/fonts/lato_italic_400.ttf
  sprinkler/assets/fonts/lato_italic_700.ttf
  sprinkler/assets/fonts/lato_normal_300.ttf
  sprinkler/assets/fonts/lato_normal_400.ttf
  sprinkler/assets/fonts/lato_normal_700.ttf
  sprinkler/assets/fonts/literata_italic_800.ttf
  sprinkler/assets/fonts/literata_normal_800.ttf
  sprinkler/assets/fonts/lora_italic_400.ttf
  sprinkler/assets/fonts/lora_italic_500.ttf
  sprinkler/assets/fonts/lora_italic_600.ttf
  sprinkler/assets/fonts/lora_italic_700.ttf
  sprinkler/assets/fonts/lora_normal_400.ttf
  sprinkler/assets/fonts/lora_normal_500.ttf
  sprinkler/assets/fonts/lora_normal_600.ttf
  sprinkler/assets/fonts/lora_normal_700.ttf
  sprinkler/assets/images/image_3-scaled.jpg
  sprinkler/functions.php
  sprinkler/parts/footer.html
  sprinkler/parts/header.html
  sprinkler/parts/post-meta.html
  sprinkler/patterns/404.php
  sprinkler/patterns/front-page.php
  sprinkler/patterns/post-meta.php
  sprinkler/patterns/search.php
  sprinkler/readme.txt
  sprinkler/screenshot.png
  sprinkler/style.css
  sprinkler/styles/.DS_Store
  sprinkler/styles/blanc-de-blanc.json
  sprinkler/styles/deep-forest_1.json
  sprinkler/styles/glass-green.json
  sprinkler/styles/sunny-lime.json
  sprinkler/styles/sycamore_1.json
  sprinkler/templates/404.html
  sprinkler/templates/archive.html
  sprinkler/templates/front-page.html
  sprinkler/templates/index.html
  sprinkler/templates/page.html
  sprinkler/templates/search.html
  sprinkler/templates/single.html
  sprinkler/theme.json
Labels: OSS Citizen

#8028 Luxus: Add theme
  luxus/assets/fonts/HK-grotesk/HankenGrotesk-Italic-VariableFont_wght.ttf
  luxus/assets/fonts/HK-grotesk/HankenGrotesk-VariableFont_wght.ttf
  luxus/assets/fonts/Montserrat-alt/montserrat-alternates_italic_100.ttf
  luxus/assets/fonts/Montserrat-alt/montserrat-alternates_italic_200.ttf
  luxus/assets/fonts/Montserrat-alt/montserrat-alternates_italic_300.ttf
  luxus/assets/fonts/Montserrat-alt/montserrat-alternates_italic_400.ttf
  luxus/assets/fonts/Montserrat-alt/montserrat-alternates_italic_500.ttf
  luxus/assets/fonts/Montserrat-alt/montserrat-alternates_italic_600.ttf
  luxus/assets/fonts/Montserrat-alt/montserrat-alternates_italic_700.ttf
  luxus/assets/fonts/Montserrat-alt/montserrat-alternates_italic_800.ttf
  luxus/assets/fonts/Montserrat-alt/montserrat-alternates_italic_900.ttf
  luxus/assets/fonts/Montserrat-alt/montserrat-alternates_normal_100.ttf
  luxus/assets/fonts/Montserrat-alt/montserrat-alternates_normal_200.ttf
  luxus/assets/fonts/Montserrat-alt/montserrat-alternates_normal_300.ttf
  luxus/assets/fonts/Montserrat-alt/montserrat-alternates_normal_400.ttf
  luxus/assets/fonts/Montserrat-alt/montserrat-alternates_normal_500.ttf
  luxus/assets/fonts/Montserrat-alt/montserrat-alternates_normal_600.ttf
  luxus/assets/fonts/Montserrat-alt/montserrat-alternates_normal_700.ttf
  luxus/assets/fonts/Montserrat-alt/montserrat-alternates_normal_800.ttf
  luxus/assets/fonts/Montserrat-alt/montserrat-alternates_normal_900.ttf
  luxus/assets/fonts/cinzel-decorative_normal_400.ttf
  luxus/assets/fonts/cinzel-decorative_normal_700.ttf
  luxus/assets/fonts/ojuju-extralight_normal_200-800.ttf
  luxus/assets/images/nail-salon.jpeg
  luxus/assets/images/rays.svg
  luxus/assets/images/wave.svg
  luxus/functions.php
  luxus/parts/footer.html
  luxus/parts/header.html
  luxus/patterns/footer.php
  luxus/patterns/header.php
  luxus/patterns/hidden-404.php
  luxus/patterns/hidden-no-search-results.php
  luxus/patterns/home.php
  luxus/patterns/services.php
  luxus/readme.txt
  luxus/screenshot.png
  luxus/style.css
  luxus/styles/boho.json
  luxus/styles/hot-pink.json
  luxus/templates/404.html
  luxus/templates/archive.html
  luxus/templates/home.html
  luxus/templates/index.html
  luxus/templates/page.html
  luxus/templates/search.html
  luxus/templates/single.html
  luxus/theme.json
Labels: New Theme

#8052 Refactor pre commit hook to be an ESM Module
  pre-commit-hook.mjs
Labels: [Type] Bug

#7880 Promoter: add theme
  promoter/assets/fonts/crimson-pro/crimson-pro_italic_400.ttf
  promoter/assets/fonts/crimson-pro/crimson-pro_italic_500.ttf
  promoter/assets/fonts/crimson-pro/crimson-pro_italic_700.ttf
  promoter/assets/fonts/crimson-pro/crimson-pro_normal_400.ttf
  promoter/assets/fonts/crimson-pro/crimson-pro_normal_500.ttf
  promoter/assets/fonts/crimson-pro/crimson-pro_normal_700.ttf
  promoter/assets/fonts/inter-tight/inter-tight_italic_400.woff2
  promoter/assets/fonts/inter-tight/inter-tight_italic_700.woff2
  promoter/assets/fonts/inter-tight/inter-tight_normal_400.woff2
  promoter/assets/fonts/inter-tight/inter-tight_normal_700.woff2
  promoter/assets/fonts/norm/Norm_italic_400.woff
  promoter/assets/fonts/norm/Norm_italic_700.woff
  promoter/assets/fonts/norm/Norm_normal_700.woff
  promoter/assets/fonts/norm/Norm_regular_400.woff
  promoter/assets/fonts/rubik/rubik_italic_300.woff2
  promoter/assets/fonts/rubik/rubik_italic_500.woff2
  promoter/assets/fonts/rubik/rubik_normal_300.woff2
  promoter/assets/fonts/rubik/rubik_normal_500.woff2
  promoter/functions.php
  promoter/parts/footer.html
  promoter/parts/header.html
  promoter/parts/post-meta.html
  promoter/patterns/404.php
  promoter/patterns/about.php
  promoter/patterns/footer.php
  promoter/patterns/header.php
  promoter/patterns/hidden-no-results.php
  promoter/patterns/home.php
  promoter/readme.txt
  promoter/screenshot.png
  promoter/style.css
  promoter/styles/ambrosia.json
  promoter/styles/aubergine.json
  promoter/styles/heavens.json
  promoter/styles/negroni.json
  promoter/styles/pianoforte.json
  promoter/templates/404.html
  promoter/templates/archive.html
  promoter/templates/home.html
  promoter/templates/index.html
  promoter/templates/page.html
  promoter/templates/search.html
  promoter/templates/single.html
  promoter/theme.json
Labels: New Theme

#7889 Feature: add theme
  feature/assets/fonts/averia-serif-libre/averia-serif-libre_italic_400.ttf
  feature/assets/fonts/averia-serif-libre/averia-serif-libre_italic_700.ttf
  feature/assets/fonts/averia-serif-libre/averia-serif-libre_normal_400.ttf
  feature/assets/fonts/averia-serif-libre/averia-serif-libre_normal_700.ttf
  feature/assets/fonts/labrada/labrada_italic_300.ttf
  feature/assets/fonts/labrada/labrada_italic_400.ttf
  feature/assets/fonts/labrada/labrada_italic_600.ttf
  feature/assets/fonts/labrada/labrada_normal_300.ttf
  feature/assets/fonts/labrada/labrada_normal_400.ttf
  feature/assets/fonts/labrada/labrada_normal_600.ttf
  feature/assets/fonts/plus-jakarta-sans/plus-jakarta-sans_italic_300.ttf
  feature/assets/fonts/plus-jakarta-sans/plus-jakarta-sans_italic_500.ttf
  feature/assets/fonts/plus-jakarta-sans/plus-jakarta-sans_italic_600.ttf
  feature/assets/fonts/plus-jakarta-sans/plus-jakarta-sans_normal_300.ttf
  feature/assets/fonts/plus-jakarta-sans/plus-jakarta-sans_normal_500.ttf
  feature/assets/fonts/plus-jakarta-sans/plus-jakarta-sans_normal_600.ttf
  feature/assets/fonts/teko/teko_normal_400.ttf
  feature/assets/fonts/teko/teko_normal_500.ttf
  feature/assets/fonts/teko/teko_normal_600.ttf
  feature/assets/images/issue-wp-theme_love-AI.png
  feature/assets/images/issue_sitelogo.png
  feature/functions.php
  feature/parts/footer-pages.html
  feature/parts/footer.html
  feature/parts/header-pages.html
  feature/parts/header.html
  feature/parts/post-meta.html
  feature/patterns/404.php
  feature/patterns/comments.php
  feature/patterns/footer-pages.php
  feature/patterns/footer.php
  feature/patterns/header-pages.php
  feature/patterns/hidden-no-results-content.php
  feature/patterns/post-meta.php
  feature/readme.txt
  feature/screenshot.jpg
  feature/style.css
  feature/styles/antiqva.json
  feature/styles/guarani.json
  feature/styles/guava.json
  feature/styles/wax.json
  feature/templates/404.html
  feature/templates/archive.html
  feature/templates/home.html
  feature/templates/index.html
  feature/templates/page.html
  feature/templates/search.html
  feature/templates/single.html
  feature/theme.json
Labels: New Theme

#7876 Brute: add theme
  brute/assets/fonts/barlow/barlow_italic_400.ttf
  brute/assets/fonts/barlow/barlow_italic_700.ttf
  brute/assets/fonts/barlow/barlow_normal_400.ttf
  brute/assets/fonts/barlow/barlow_normal_700.ttf
  brute/assets/fonts/d-din/d-din-exp_italic_400.ttf
  brute/assets/fonts/d-din/d-din-exp_normal_400.ttf
  brute/assets/fonts/rubik/rubik_italic_300.ttf
  brute/assets/fonts/rubik/rubik_normal_300.ttf
  brute/assets/images/architecture-structure-sky-roof-building-skyscraper-56714.jpg
  brute/assets/images/blue-architecture-sky-daytime-brutalist-architecture-line-1571681-pxhere.com_-1.jpg
  brute/functions.php
  brute/parts/footer.html
  brute/parts/header.html
  brute/parts/post-meta.html
  brute/parts/sidebar.html
  brute/patterns/404.php
  brute/patterns/comments.php
  brute/patterns/footer.php
  brute/patterns/front-page.php
  brute/patterns/header.php
  brute/patterns/hidden-no-results-content.php
  brute/patterns/home.php
  brute/patterns/sidebar.php
  brute/patterns/single.php
  brute/readme.txt
  brute/screenshot.png
  brute/style.css
  brute/styles/cement.json
  brute/styles/charcoal.json
  brute/styles/marble.json
  brute/templates/404.html
  brute/templates/archive.html
  brute/templates/front-page.html
  brute/templates/home.html
  brute/templates/index.html
  brute/templates/page.html
  brute/templates/search.html
  brute/templates/single.html
  brute/theme.json
Labels: New Theme

#8087 Massimo: add theme
  massimo/assets/fonts/besley/besley_italic_400.ttf
  massimo/assets/fonts/besley/besley_italic_700.ttf
  massimo/assets/fonts/besley/besley_normal_400.ttf
  massimo/assets/fonts/besley/besley_normal_700.ttf
  massimo/assets/fonts/involve/involve_italic_400.ttf
  massimo/assets/fonts/involve/involve_italic_700.ttf
  massimo/assets/fonts/involve/involve_normal_400.ttf
  massimo/assets/fonts/involve/involve_normal_700.ttf
  massimo/assets/fonts/libre-bodoni/libre-bodoni_italic_400.ttf
  massimo/assets/fonts/libre-bodoni/libre-bodoni_italic_700.ttf
  massimo/assets/fonts/libre-bodoni/libre-bodoni_normal_400.ttf
  massimo/assets/fonts/libre-bodoni/libre-bodoni_normal_700.ttf
  massimo/assets/fonts/overused-grotesk/overused-grotesk_italic_400.woff2
  massimo/assets/fonts/overused-grotesk/overused-grotesk_italic_500.woff2
  massimo/assets/fonts/overused-grotesk/overused-grotesk_italic_600.woff2
  massimo/assets/fonts/overused-grotesk/overused-grotesk_normal_400.woff2
  massimo/assets/fonts/overused-grotesk/overused-grotesk_normal_500.woff2
  massimo/assets/fonts/overused-grotesk/overused-grotesk_normal_600.woff2
  massimo/assets/fonts/times-newer-roman/times-newer-roman_italic_400.ttf
  massimo/assets/fonts/times-newer-roman/times-newer-roman_italic_700.ttf
  massimo/assets/fonts/times-newer-roman/times-newer-roman_normal_400.ttf
  massimo/assets/fonts/times-newer-roman/times-newer-roman_normal_700.ttf
  massimo/functions.php
  massimo/parts/footer.html
  massimo/parts/header-pages.html
  massimo/parts/header.html
  massimo/parts/post-meta.html
  massimo/patterns/404.php
  massimo/patterns/archive.php
  massimo/patterns/comments.php
  massimo/patterns/footer.php
  massimo/patterns/header-pages.php
  massimo/patterns/header.php
  massimo/patterns/hidden-no-results-content.php
  massimo/patterns/home.php
  massimo/patterns/index.php
  massimo/patterns/search.php
  massimo/patterns/single.php
  massimo/readme.txt
  massimo/screenshot.png
  massimo/style.css
  massimo/styles/bodoni.json
  massimo/styles/century.json
  massimo/styles/futura.json
  massimo/styles/times.json
  massimo/templates/404.html
  massimo/templates/archive.html
  massimo/templates/home.html
  massimo/templates/index.html
  massimo/templates/page.html
  massimo/templates/search.html
  massimo/templates/single.html
  massimo/theme.json
Labels: New Theme

#7874 JazzyGrid: add theme
  jazzygrid/assets/fonts/d-din/d-din-condensed_normal_400.woff2
  jazzygrid/assets/fonts/rubik/rubik_italic_300.ttf
  jazzygrid/assets/fonts/rubik/rubik_italic_600.ttf
  jazzygrid/assets/fonts/rubik/rubik_normal_300.ttf
  jazzygrid/assets/fonts/rubik/rubik_normal_600.ttf
  jazzygrid/assets/images/beach-sea-coast-water-ocean-horizon.jpg
  jazzygrid/assets/images/img-cover_trumpeteer.png
  jazzygrid/assets/images/img_trumpet-detail.png
  jazzygrid/functions.php
  jazzygrid/parts/footer.html
  jazzygrid/parts/header.html
  jazzygrid/parts/post-meta.html
  jazzygrid/patterns/404.php
  jazzygrid/patterns/archive.php
  jazzygrid/patterns/comments.php
  jazzygrid/patterns/footer.php
  jazzygrid/patterns/header.php
  jazzygrid/patterns/hidden-no-results-content.php
  jazzygrid/patterns/home.php
  jazzygrid/patterns/index.php
  jazzygrid/patterns/search.php
  jazzygrid/readme.txt
  jazzygrid/screenshot.png
  jazzygrid/style.css
  jazzygrid/styles/grapevine.json
  jazzygrid/styles/retro.json
  jazzygrid/styles/watermelon.json
  jazzygrid/templates/404.html
  jazzygrid/templates/archive.html
  jazzygrid/templates/home.html
  jazzygrid/templates/index.html
  jazzygrid/templates/page.html
  jazzygrid/templates/search.html
  jazzygrid/templates/single.html
  jazzygrid/theme.json
Labels: Ready to launch

#8090 Bump node version for theme version workflow
  .github/workflows/version-bump.yml
Labels: [Type] Bug

#7888 Message: add theme
  message/assets/fonts/inter_normal_400.ttf
  message/assets/fonts/inter_normal_700.ttf
  message/assets/images/avatar.jpg
  message/assets/images/header_grad-pages.png
  message/assets/images/header_gradient.png
  message/functions.php
  message/parts/footer.html
  message/parts/header-pages.html
  message/parts/header.html
  message/parts/post-meta.html
  message/patterns/404.php
  message/patterns/archive.php
  message/patterns/comments.php
  message/patterns/footer.php
  message/patterns/header.php
  message/patterns/hidden-no-results-content.php
  message/patterns/home.php
  message/patterns/index.php
  message/patterns/page.php
  message/patterns/search.php
  message/patterns/single.php
  message/readme.txt
  message/screenshot.png
  message/style.css
  message/styles/avocado.json
  message/styles/lightmode.json
  message/styles/sunflower.json
  message/templates/404.html
  message/templates/archive.html
  message/templates/home.html
  message/templates/index.html
  message/templates/page.html
  message/templates/search.html
  message/templates/single.html
  message/theme.json
Labels: Ready to launch

#8101 Course Release 1.3.9
  course/readme.txt
  course/style.css
  course/templates/search.html
  course/templates/single-column-featured-title.html
  course/templates/single.html
Labels: [Theme] Course

#8053 Escape patterns in directory
  theme-utils.mjs
Labels: [Type] Enhancement

#8170 Add theme-check action
  .github/workflows/theme-check.yml
Labels: Tools, Automation

#8154 Bysshe: Add theme
  bysshe/assets/fonts/roboto-serif_italic_100.ttf
  bysshe/assets/fonts/roboto-serif_italic_200.ttf
  bysshe/assets/fonts/roboto-serif_italic_300.ttf
  bysshe/assets/fonts/roboto-serif_italic_400.ttf
  bysshe/assets/fonts/roboto-serif_italic_500.ttf
  bysshe/assets/fonts/roboto-serif_italic_600.ttf
  bysshe/assets/fonts/roboto-serif_italic_700.ttf
  bysshe/assets/fonts/roboto-serif_italic_800.ttf
  bysshe/assets/fonts/roboto-serif_italic_900.ttf
  bysshe/assets/fonts/roboto-serif_normal_100.ttf
  bysshe/assets/fonts/roboto-serif_normal_200.ttf
  bysshe/assets/fonts/roboto-serif_normal_300.ttf
  bysshe/assets/fonts/roboto-serif_normal_400.ttf
  bysshe/assets/fonts/roboto-serif_normal_500.ttf
  bysshe/assets/fonts/roboto-serif_normal_600.ttf
  bysshe/assets/fonts/roboto-serif_normal_700.ttf
  bysshe/assets/fonts/roboto-serif_normal_800.ttf
  bysshe/assets/fonts/roboto-serif_normal_900.ttf
  bysshe/assets/images/Percy_Bysshe_Shelley_by_Alfred_Clint.jpg
  bysshe/assets/images/wolfgang-hasselmann-pVr6wvUneMk-unsplash-scaled.jpg
  bysshe/functions.php
  bysshe/patterns/404.php
  bysshe/patterns/archive.php
  bysshe/patterns/index.php
  bysshe/patterns/page.php
  bysshe/patterns/search.php
  bysshe/patterns/single.php
  bysshe/readme.txt
  bysshe/screenshot.png
  bysshe/style.css
  bysshe/templates/404.html
  bysshe/templates/archive.html
  bysshe/templates/index.html
  bysshe/templates/page.html
  bysshe/templates/search.html
  bysshe/templates/single.html
  bysshe/theme.json
Labels: Ready to launch

#8082 Impressionist: Add new theme
  impressionist/assets/fonts/beth-ellen_normal_400.ttf
  impressionist/assets/fonts/cardo_italic_400.ttf
  impressionist/assets/fonts/cardo_normal_400.ttf
  impressionist/assets/fonts/cardo_normal_700.ttf
  impressionist/assets/images/impressionist-author-image-edited.jpg
  impressionist/assets/images/impressionist-home-bg.jpg
  impressionist/functions.php
  impressionist/parts/comments.html
  impressionist/parts/footer.html
  impressionist/parts/header.html
  impressionist/parts/post-meta.html
  impressionist/patterns/404.php
  impressionist/patterns/biography.php
  impressionist/patterns/comments.php
  impressionist/patterns/footer.php
  impressionist/patterns/front-page.php
  impressionist/patterns/hidden-no-results-content.php
  impressionist/patterns/index.php
  impressionist/patterns/post-meta.php
  impressionist/patterns/text-slashes.php
  impressionist/readme.txt
  impressionist/screenshot.png
  impressionist/style.css
  impressionist/templates/404.html
  impressionist/templates/archive.html
  impressionist/templates/front-page.html
  impressionist/templates/index.html
  impressionist/templates/page.html
  impressionist/templates/search.html
  impressionist/templates/single.html
  impressionist/theme.json
Labels: Ready to launch

#8125 Colorstream: add theme
  colorstream/assets/fonts/bricolage-grotesque/bricolage-grotesque_normal_400.ttf
  colorstream/assets/fonts/bricolage-grotesque/bricolage-grotesque_normal_700.ttf
  colorstream/assets/fonts/elite-math-new/elite-math-new.ttf
  colorstream/assets/fonts/libre-caslon-text/libre-caslon-text_italic_400.ttf
  colorstream/assets/fonts/libre-caslon-text/libre-caslon-text_normal_400.ttf
  colorstream/assets/fonts/libre-caslon-text/libre-caslon-text_normal_700.ttf
  colorstream/assets/fonts/libre-caslon/libre-caslon-condensed_normal_400.woff2
  colorstream/assets/fonts/libre-caslon/libre-caslon-condensed_normal_700.woff2
  colorstream/assets/fonts/overused-grotesk/overused-grotesk_italic_400.woff2
  colorstream/assets/fonts/overused-grotesk/overused-grotesk_italic_500.woff2
  colorstream/assets/fonts/overused-grotesk/overused-grotesk_italic_600.woff2
  colorstream/assets/fonts/overused-grotesk/overused-grotesk_normal_400.woff2
  colorstream/assets/fonts/overused-grotesk/overused-grotesk_normal_500.woff2
  colorstream/assets/fonts/overused-grotesk/overused-grotesk_normal_600.woff2
  colorstream/assets/fonts/space-grotesk/space-grotesk_normal_300.ttf
  colorstream/assets/fonts/space-grotesk/space-grotesk_normal_400.ttf
  colorstream/assets/fonts/space-grotesk/space-grotesk_normal_600.ttf
  colorstream/assets/fonts/special-elite/special-elite_normal_400.woff2
  colorstream/functions.php
  colorstream/parts/footer.html
  colorstream/parts/header.html
  colorstream/parts/post-meta.html
  colorstream/patterns/404.php
  colorstream/patterns/archive.php
  colorstream/patterns/comments.php
  colorstream/patterns/footer.php
  colorstream/patterns/front-page.php
  colorstream/patterns/hidden-no-results-content.php
  colorstream/patterns/home.php
  colorstream/patterns/index.php
  colorstream/patterns/page.php
  colorstream/patterns/search.php
  colorstream/patterns/single.php
  colorstream/readme.txt
  colorstream/screenshot.png
  colorstream/style.css
  colorstream/styles/autunnale.json
  colorstream/styles/pastel-garden.json
  colorstream/styles/remington.json
  colorstream/templates/404.html
  colorstream/templates/archive.html
  colorstream/templates/front-page.html
  colorstream/templates/home.html
  colorstream/templates/index.html
  colorstream/templates/page.html
  colorstream/templates/search.html
  colorstream/templates/single.html
  colorstream/theme.json
Labels: Ready to launch

#8143 Cubico: add theme
  cubico/assets/fonts/figtree/figtree_italic_500.ttf
  cubico/assets/fonts/figtree/figtree_normal_500.ttf
  cubico/assets/fonts/inter-tight/inter-tight_italic_400.woff2
  cubico/assets/fonts/inter-tight/inter-tight_italic_700.woff2
  cubico/assets/fonts/inter-tight/inter-tight_normal_400.woff2
  cubico/assets/fonts/inter-tight/inter-tight_normal_700.woff2
  cubico/assets/fonts/open-runde/open-runde_normal_600.woff2
  cubico/assets/fonts/open-runde/open-runde_normal_700.woff2
  cubico/functions.php
  cubico/parts/footer.html
  cubico/parts/header-headline.html
  cubico/parts/header-sitelogo.html
  cubico/parts/header.html
  cubico/parts/post-meta.html
  cubico/patterns/404.php
  cubico/patterns/comments.php
  cubico/patterns/footer.php
  cubico/patterns/header-sitelogo.php
  cubico/patterns/header.php
  cubico/patterns/hidden-no-results-content.php
  cubico/readme.txt
  cubico/screenshot.png
  cubico/style.css
  cubico/styles/darkmode.json
  cubico/templates/404.html
  cubico/templates/archive.html
  cubico/templates/home.html
  cubico/templates/index.html
  cubico/templates/page.html
  cubico/templates/search.html
  cubico/templates/single.html
  cubico/theme.json
Labels: Ready to launch

#8124 Add Alley-Oop Theme
  alleyoop/assets/fonts/hezaedrus_italic_400.ttf
  alleyoop/assets/fonts/hezaedrus_italic_700.ttf
  alleyoop/assets/fonts/hezaedrus_normal_400.ttf
  alleyoop/assets/fonts/hezaedrus_normal_700.ttf
  alleyoop/assets/fonts/tektur-tight_normal_900.ttf
  alleyoop/assets/images/hero_topviewred.jpg
  alleyoop/assets/images/hero_topviewshadowed.jpg
  alleyoop/functions.php
  alleyoop/parts/comments.html
  alleyoop/parts/footer.html
  alleyoop/parts/header-with-cover.html
  alleyoop/parts/header-with-sticky-post.html
  alleyoop/parts/header.html
  alleyoop/patterns/404.php
  alleyoop/patterns/archive.php
  alleyoop/patterns/footer.php
  alleyoop/patterns/front-page.php
  alleyoop/patterns/header-with-cover.php
  alleyoop/patterns/header-with-sticky-post.php
  alleyoop/patterns/index.php
  alleyoop/patterns/search.php
  alleyoop/readme.txt
  alleyoop/screenshot.png
  alleyoop/style.css
  alleyoop/styles/sundown.json
  alleyoop/styles/vanilla.json
  alleyoop/templates/404.html
  alleyoop/templates/archive.html
  alleyoop/templates/front-page.html
  alleyoop/templates/index.html
  alleyoop/templates/page.html
  alleyoop/templates/search.html
  alleyoop/templates/single.html
  alleyoop/theme.json
Labels: Ready to launch

#8130 Colorloops: add theme
  colorloops/assets/fonts/bricolage-grotesque/bricolage-grotesque_normal_400.ttf
  colorloops/assets/fonts/bricolage-grotesque/bricolage-grotesque_normal_700.ttf
  colorloops/assets/fonts/libre-caslon-text/libre-caslon-text_italic_400.ttf
  colorloops/assets/fonts/libre-caslon-text/libre-caslon-text_normal_400.ttf
  colorloops/assets/fonts/libre-caslon-text/libre-caslon-text_normal_700.ttf
  colorloops/assets/fonts/libre-caslon/libre-caslon-condensed_normal_400.woff2
  colorloops/assets/fonts/libre-caslon/libre-caslon-condensed_normal_700.woff2
  colorloops/assets/fonts/open-sauce-sans/open-sauce-sans_italic_400.ttf
  colorloops/assets/fonts/open-sauce-sans/open-sauce-sans_italic_500.ttf
  colorloops/assets/fonts/open-sauce-sans/open-sauce-sans_normal_400.ttf
  colorloops/assets/fonts/open-sauce-sans/open-sauce-sans_normal_500.ttf
  colorloops/assets/fonts/overpass-mono/overpass-mono_normal_300.ttf
  colorloops/assets/fonts/overpass-mono/overpass-mono_normal_600.ttf
  colorloops/functions.php
  colorloops/parts/footer.html
  colorloops/parts/header.html
  colorloops/parts/post-meta.html
  colorloops/parts/sidebar.html
  colorloops/patterns/404.php
  colorloops/patterns/footer.php
  colorloops/patterns/sidebar.php
  colorloops/readme.txt
  colorloops/screenshot.png
  colorloops/style.css
  colorloops/styles/autunnale.json
  colorloops/styles/bright-garden.json
  colorloops/templates/404.html
  colorloops/templates/archive.html
  colorloops/templates/front-page.html
  colorloops/templates/home.html
  colorloops/templates/index.html
  colorloops/templates/page.html
  colorloops/templates/search.html
  colorloops/templates/single.html
  colorloops/theme.json
Labels: Ready to launch

#8206 Assembler: Remove inherited color styling from linked headings
  assembler/style.css
Labels: [Theme] Assembler, Groundskeeping

#8208 Fix footer validation and spacing issue
  assembler/parts/footer.html
Labels: [Type] Bug, [Theme] Assembler

#8148 Add Startorg
  startorg/assets/fonts/plus-jakarta-sans_italic_300.ttf
  startorg/assets/fonts/plus-jakarta-sans_italic_400.ttf
  startorg/assets/fonts/plus-jakarta-sans_italic_500.ttf
  startorg/assets/fonts/plus-jakarta-sans_italic_600.ttf
  startorg/assets/fonts/plus-jakarta-sans_italic_700.ttf
  startorg/assets/fonts/plus-jakarta-sans_normal_300.ttf
  startorg/assets/fonts/plus-jakarta-sans_normal_400.ttf
  startorg/assets/fonts/plus-jakarta-sans_normal_500.ttf
  startorg/assets/fonts/plus-jakarta-sans_normal_600.ttf
  startorg/assets/fonts/plus-jakarta-sans_normal_700.ttf
  startorg/assets/images/home_image.jpg
  startorg/assets/images/home_image_2.jpg
  startorg/assets/images/home_image_3.jpg
  startorg/assets/images/home_image_4.jpg
  startorg/assets/images/home_image_5.jpg
  startorg/assets/videos/roar_hero_banner.webm
  startorg/functions.php
  startorg/parts/footer-global.html
  startorg/parts/footer.html
  startorg/parts/header-global.html
  startorg/parts/header.html
  startorg/parts/post-meta.html
  startorg/patterns/404.php
  startorg/patterns/archive.php
  startorg/patterns/cover-with-quote.php
  startorg/patterns/footer-global.php
  startorg/patterns/footer.php
  startorg/patterns/header-global.php
  startorg/patterns/header.php
  startorg/patterns/home.php
  startorg/patterns/index.php
  startorg/patterns/latest-posts.php
  startorg/patterns/media-and-text.php
  startorg/patterns/search.php
  startorg/patterns/single.php
  startorg/patterns/subscribe.php
  startorg/patterns/three-columns-banner.php
  startorg/readme.txt
  startorg/screenshot.png
  startorg/style.css
  startorg/styles/frozen.json
  startorg/templates/404.html
  startorg/templates/archive.html
  startorg/templates/home.html
  startorg/templates/index.html
  startorg/templates/page.html
  startorg/templates/search.html
  startorg/templates/single.html
  startorg/theme.json
Labels: Ready to launch
