Repository Automattic/themes, pull requests merged in 2024-11, with the labels that each got.

#8333 Handle specific themes in versionBumpThemes
  theme-utils.mjs
Labels: Tools

#8368 Remove some themes from dotorg ignore list
  .dotorg-ignore
Labels: Tools

#8360 Downtown: add theme
  downtown/assets/fonts/anticva/Anticva_regular_400.otf
  downtown/assets/fonts/apfel-grotezk/apfel-grotezk_normal_400.otf
  downtown/assets/fonts/apfel-grotezk/apfel-grotezk_normal_600.otf
  downtown/assets/fonts/apfel-grotezk/apfel-grotezk_normal_700.otf
  downtown/assets/fonts/coconat/coconat_normal_400.woff2
  downtown/assets/fonts/coconat/coconat_normal_600.woff2
  downtown/assets/fonts/coconat/coconat_normal_700.woff2
  downtown/assets/fonts/ibarra-real-nova/ibarra-real-nova_italic_wght.ttf
  downtown/assets/fonts/ibarra-real-nova/ibarra-real-nova_normal_wght.ttf
  downtown/assets/fonts/libre-caslon-text/libre-caslon-text_italic_400.woff2
  downtown/assets/fonts/libre-caslon-text/libre-caslon-text_normal_400.woff2
  downtown/assets/fonts/libre-caslon-text/libre-caslon-text_normal_700.woff2
  downtown/assets/fonts/manrope/manrope_normal_300.ttf
  downtown/assets/fonts/manrope/manrope_normal_400.ttf
  downtown/assets/fonts/manrope/manrope_normal_600.ttf
  downtown/assets/fonts/manrope/manrope_normal_700.ttf
  downtown/assets/fonts/sinistre/sinistre_normal_wght.ttf
  downtown/assets/fonts/tilda-sans/tilda-sans_normal_300.woff2
  downtown/assets/fonts/tilda-sans/tilda-sans_normal_400.woff2
  downtown/assets/fonts/tilda-sans/tilda-sans_normal_500.woff2
  downtown/assets/fonts/tilda-sans/tilda-sans_normal_600.woff2
  downtown/assets/fonts/tilda-sans/tilda-sans_normal_700.woff2
  downtown/assets/images/downtown_beach-sea-coast-water-nature-outdoor.jpg
  downtown/functions.php
  downtown/parts/comments.html
  downtown/parts/footer.html
  downtown/parts/header.html
  downtown/parts/post-meta.html
  downtown/patterns/404.php
  downtown/patterns/archive.php
  downtown/patterns/footer.php
  downtown/patterns/front-page.php
  downtown/patterns/index.php
  downtown/patterns/post-meta.php
  downtown/patterns/search.php
  downtown/readme.txt
  downtown/screenshot.jpg
  downtown/style.css
  downtown/styles/ebony-city.json
  downtown/styles/mauve-town.json
  downtown/styles/quarry-burg.json
  downtown/styles/tropic-port.json
  downtown/styles/wood-place.json
  downtown/templates/404.html
  downtown/templates/archive.html
  downtown/templates/front-page.html
  downtown/templates/index.html
  downtown/templates/page-about-us.html
  downtown/templates/page.html
  downtown/templates/search.html
  downtown/templates/single.html
  downtown/theme.json
Labels: Ready to launch

#8409 Fix Lucette typography style JSON validation
  assembler/styles/typography/09-lucette.json
Labels: [Type] Bug

#8424 Urbem: add theme
  urbem/assets/fonts/anticva/Anticva_regular_400.otf
  urbem/assets/fonts/apfel-grotezk/apfel-grotezk_normal_400.otf
  urbem/assets/fonts/apfel-grotezk/apfel-grotezk_normal_600.otf
  urbem/assets/fonts/apfel-grotezk/apfel-grotezk_normal_700.otf
  urbem/assets/fonts/coconat/coconat_normal_400.woff2
  urbem/assets/fonts/coconat/coconat_normal_600.woff2
  urbem/assets/fonts/coconat/coconat_normal_700.woff2
  urbem/assets/fonts/ibarra-real-nova/ibarra-real-nova_italic_wght.ttf
  urbem/assets/fonts/ibarra-real-nova/ibarra-real-nova_normal_wght.ttf
  urbem/assets/fonts/libre-caslon-text/libre-caslon-text_italic_400.woff2
  urbem/assets/fonts/libre-caslon-text/libre-caslon-text_normal_400.woff2
  urbem/assets/fonts/libre-caslon-text/libre-caslon-text_normal_700.woff2
  urbem/assets/fonts/manrope/manrope_normal_300.ttf
  urbem/assets/fonts/manrope/manrope_normal_400.ttf
  urbem/assets/fonts/manrope/manrope_normal_600.ttf
  urbem/assets/fonts/manrope/manrope_normal_700.ttf
  urbem/assets/fonts/sinistre/sinistre_normal_wght.ttf
  urbem/assets/fonts/tilda-sans/tilda-sans_normal_300.woff2
  urbem/assets/fonts/tilda-sans/tilda-sans_normal_400.woff2
  urbem/assets/fonts/tilda-sans/tilda-sans_normal_500.woff2
  urbem/assets/fonts/tilda-sans/tilda-sans_normal_600.woff2
  urbem/assets/fonts/tilda-sans/tilda-sans_normal_700.woff2
  urbem/assets/images/urbem_beach-sea-coast-water-nature-outdoor.jpg
  urbem/functions.php
  urbem/parts/comments.html
  urbem/parts/footer.html
  urbem/parts/header.html
  urbem/parts/post-meta.html
  urbem/patterns/404.php
  urbem/patterns/archive.php
  urbem/patterns/footer.php
  urbem/patterns/front-page.php
  urbem/patterns/index.php
  urbem/patterns/post-meta.php
  urbem/patterns/search.php
  urbem/readme.txt
  urbem/screenshot.jpg
  urbem/style.css
  urbem/styles/ebony-city.json
  urbem/styles/mauve-town.json
  urbem/styles/quarry-burg.json
  urbem/styles/tropic-port.json
  urbem/styles/wood-place.json
  urbem/templates/404.html
  urbem/templates/archive.html
  urbem/templates/front-page.html
  urbem/templates/index.html
  urbem/templates/page-about-us.html
  urbem/templates/page.html
  urbem/templates/search.html
  urbem/templates/single.html
  urbem/theme.json
Labels: Ready to launch

#8410 Vueo: add theme
  vueo/assets/fonts/apfel-grotezk/apfel-grotezk_normal_400.otf
  vueo/assets/fonts/apfel-grotezk/apfel-grotezk_normal_600.otf
  vueo/assets/fonts/apfel-grotezk/apfel-grotezk_normal_700.otf
  vueo/assets/fonts/basicallyamono/basicallyamono_normal_400.woff2
  vueo/assets/fonts/basicallyamono/basicallyamono_normal_500.woff2
  vueo/assets/fonts/basicallyamono/basicallyamono_normal_700.woff2
  vueo/assets/fonts/bdo-grotesk/bdo-grotesk_normal_wght.woff2
  vueo/assets/fonts/hauora/hauora_normal_400.woff2
  vueo/assets/fonts/hauora/hauora_normal_500.woff2
  vueo/assets/fonts/hauora/hauora_normal_700.woff2
  vueo/assets/fonts/sinar-reversed/sinar-reversed_normal_400.woff2
  vueo/assets/fonts/sinar-reversed/sinar-reversed_normal_500.woff2
  vueo/assets/fonts/sinar-reversed/sinar-reversed_normal_700.woff2
  vueo/functions.php
  vueo/parts/comments.html
  vueo/parts/footer-pages.html
  vueo/parts/footer.html
  vueo/parts/header-pages.html
  vueo/parts/header.html
  vueo/patterns/404.php
  vueo/patterns/archive.php
  vueo/patterns/footer-pages.php
  vueo/patterns/footer.php
  vueo/patterns/header-pages.php
  vueo/patterns/header.php
  vueo/patterns/index.php
  vueo/patterns/search.php
  vueo/readme.txt
  vueo/screenshot.jpg
  vueo/style.css
  vueo/styles/chestnut.json
  vueo/styles/claret.json
  vueo/styles/dry.json
  vueo/styles/expanse.json
  vueo/styles/moss.json
  vueo/templates/404.html
  vueo/templates/archive.html
  vueo/templates/front-page.html
  vueo/templates/index.html
  vueo/templates/page-about-us.html
  vueo/templates/page.html
  vueo/templates/search.html
  vueo/templates/single.html
  vueo/theme.json
Labels: Ready to launch

#8434 Attempt to fix dotorg deploy script
  deploy-dotorg.sh
Labels: Tools

#8415 Message: Fix for SyntaxHighlighter overflow and editor contrast
  message/style.css
Labels: [Type] Bug, Groundskeeping

#8414 Loic: Add fix for SyntaxHighlighter max-width bug
  loic/style.css
Labels: [Type] Bug, Groundskeeping

#8441 Refactor dotorg deploy rsync step
  deploy-dotorg.sh
Labels: Tools

#8408 Update playground-pr-preview ref
  .github/workflows/preview-theme.yml
Labels: Tools

#8420 Improve spacing within post content with content and patterns
  assembler/style.css
  assembler/theme.json
Labels: [Type] Bug, [Theme] Assembler

#8422 Curating Assembler color variations
  assembler/styles/colors/08-sandstone.json
  assembler/styles/colors/09-moss.json
  assembler/styles/colors/10-noir.json
  assembler/styles/colors/11-onyx.json
Labels: [Theme] Assembler

#8439 Streamer: add theme
  streamer/assets/fonts/departure-mono/departure-mono_normal_400.woff2
  streamer/assets/fonts/geist-mono/geist-mono_normal_400.woff2
  streamer/assets/fonts/geist-mono/geist-mono_normal_500.woff2
  streamer/assets/fonts/geist-mono/geist-mono_normal_700.woff2
  streamer/assets/fonts/geist/geist_normal_400.woff2
  streamer/assets/fonts/geist/geist_normal_500.woff2
  streamer/assets/fonts/geist/geist_normal_700.woff2
  streamer/assets/fonts/hezaedrus/hezaedrus_italic_400.ttf
  streamer/assets/fonts/hezaedrus/hezaedrus_italic_700.ttf
  streamer/assets/fonts/hezaedrus/hezaedrus_normal_400.ttf
  streamer/assets/fonts/hezaedrus/hezaedrus_normal_700.ttf
  streamer/assets/fonts/jaro/jaro_normal_400.ttf
  streamer/assets/fonts/jaro/jaro_normal_500.ttf
  streamer/assets/fonts/jaro/jaro_normal_700.ttf
  streamer/assets/fonts/lc-mogi/lc-mogi_normal_vf.woff2
  streamer/assets/fonts/utara/utara_normal_400.woff2
  streamer/assets/fonts/utara/utara_normal_500.woff2
  streamer/assets/fonts/utara/utara_normal_700.woff2
  streamer/functions.php
  streamer/parts/comments.html
  streamer/parts/footer.html
  streamer/parts/header.html
  streamer/parts/post-meta.html
  streamer/patterns/404.php
  streamer/patterns/archive.php
  streamer/patterns/footer.php
  streamer/patterns/home.php
  streamer/patterns/index.php
  streamer/patterns/post-meta.php
  streamer/patterns/search.php
  streamer/readme.txt
  streamer/screenshot.jpg
  streamer/style.css
  streamer/styles/livid.json
  streamer/styles/persimmon.json
  streamer/styles/plunge.json
  streamer/templates/404.html
  streamer/templates/archive.html
  streamer/templates/home.html
  streamer/templates/index.html
  streamer/templates/page-full-width.html
  streamer/templates/page.html
  streamer/templates/search.html
  streamer/templates/single.html
  streamer/theme.json
Labels: Ready to launch

#8423 Simplify page with title template and fix title alignment
  assembler/patterns/template-page-w-title.php
  assembler/templates/template-page-w-title.html
Labels: [Type] Bug, [Theme] Assembler

#8421 Improve Assembler typography styles
  assembler/assets/fonts/bricolage-grotesque/BricolageGrotesque-VariableFont_opsz,wdth,wght.ttf
  assembler/assets/fonts/bricolage-grotesque/OFL.txt
  assembler/assets/fonts/cardo/OFL.txt
  assembler/assets/fonts/cardo/cardo_italic_400.woff2
  assembler/assets/fonts/cardo/cardo_normal_400.woff2
  assembler/assets/fonts/cardo/cardo_normal_700.woff2
  assembler/assets/fonts/dm-serif-display/DMSerifDisplay-Italic.ttf
  assembler/assets/fonts/dm-serif-display/DMSerifDisplay-Regular.ttf
  assembler/assets/fonts/dm-serif-display/OFL.txt
  assembler/assets/fonts/libre-baskerville/LibreBaskerville-Bold.ttf
  assembler/assets/fonts/libre-baskerville/LibreBaskerville-Italic.ttf
  assembler/assets/fonts/libre-baskerville/LibreBaskerville-Regular.ttf
  assembler/assets/fonts/libre-baskerville/OFL.txt
  assembler/assets/fonts/rufina/OFL.txt
  assembler/assets/fonts/rufina/Rufina-Bold.ttf
  assembler/assets/fonts/rufina/Rufina-Regular.ttf
  assembler/assets/fonts/vina-sans/OFL.txt
  assembler/assets/fonts/vina-sans/VinaSans-Regular.ttf
  assembler/styles/typography/01-figtree.json
  assembler/styles/typography/02-sora.json
  assembler/styles/typography/03-rubik.json
  assembler/styles/typography/04-fjalla.json
  assembler/styles/typography/05-gabarito.json
  assembler/styles/typography/06-fahkwang.json
  assembler/styles/typography/07-messapia-dm-sans.json
  assembler/styles/typography/08-fraunces.json
  assembler/styles/typography/09-ibarra.json
  assembler/styles/typography/10-lucette.json
  assembler/styles/typography/11-instrument-serif-mono.json
  assembler/styles/typography/12-instrument-serif-urbanist.json
  assembler/styles/typography/13-instrument-serif-italic.json
  assembler/styles/typography/13-rufina.json
  assembler/styles/typography/14-syne.json
  assembler/theme.json
Labels: [Type] Enhancement, [Theme] Assembler

#8186 Theme Assembler: Fix radio control height css issue
  assembler/style.css
Labels: [Theme] Assembler
