Repository Automattic/themes, pull requests merged in 2024-04, with the labels that each got.

#7717 Block Canvas: Add standard spacing presets
  block-canvas/theme.json
Labels: [Theme] Block Canvas

#7729 Assembler: Add fonts
  assembler/assets/fonts/dm-mono/DMMono-Italic.ttf
  assembler/assets/fonts/dm-mono/DMMono-Light.ttf
  assembler/assets/fonts/dm-mono/DMMono-Medium.ttf
  assembler/assets/fonts/dm-mono/DMMono-MediumItalic.ttf
  assembler/assets/fonts/dm-mono/DMMono-Regular.ttf
  assembler/assets/fonts/dm-mono/OFL.txt
  assembler/assets/fonts/lucette/Lucette-Regular.woff2
  assembler/assets/fonts/lucette/Lucette-Regularitalic.woff2
  assembler/assets/fonts/lucette/OFL.txt
  assembler/assets/fonts/messapia/Messapia-Bold.woff2
  assembler/assets/fonts/messapia/Messapia.woff2
  assembler/assets/fonts/messapia/OFL.txt
  assembler/theme.json
Labels: [Type] Enhancement

#6905 Kiosko: add theme
  kiosko/assets/fonts/oswald/oswald_italic_200.ttf
  kiosko/assets/fonts/oswald/oswald_italic_300.ttf
  kiosko/assets/fonts/oswald/oswald_italic_400.ttf
  kiosko/assets/fonts/oswald/oswald_italic_500.ttf
  kiosko/assets/fonts/oswald/oswald_italic_600.ttf
  kiosko/assets/fonts/oswald/oswald_italic_700.ttf
  kiosko/assets/fonts/oswald/oswald_italic_800.ttf
  kiosko/assets/fonts/oswald/oswald_normal_200.ttf
  kiosko/assets/fonts/oswald/oswald_normal_300.ttf
  kiosko/assets/fonts/oswald/oswald_normal_400.ttf
  kiosko/assets/fonts/oswald/oswald_normal_500.ttf
  kiosko/assets/fonts/oswald/oswald_normal_600.ttf
  kiosko/assets/fonts/oswald/oswald_normal_700.ttf
  kiosko/assets/fonts/oswald/oswald_normal_800.ttf
  kiosko/assets/fonts/roboto/Roboto-Black.ttf
  kiosko/assets/fonts/roboto/Roboto-BlackItalic.ttf
  kiosko/assets/fonts/roboto/Roboto-Bold.ttf
  kiosko/assets/fonts/roboto/Roboto-BoldItalic.ttf
  kiosko/assets/fonts/roboto/Roboto-Italic.ttf
  kiosko/assets/fonts/roboto/Roboto-Light.ttf
  kiosko/assets/fonts/roboto/Roboto-LightItalic.ttf
  kiosko/assets/fonts/roboto/Roboto-Medium.ttf
  kiosko/assets/fonts/roboto/Roboto-MediumItalic.ttf
  kiosko/assets/fonts/roboto/Roboto-Regular.ttf
  kiosko/assets/fonts/roboto/Roboto-Thin.ttf
  kiosko/assets/fonts/roboto/Roboto-ThinItalic.ttf
  kiosko/functions.php
  kiosko/parts/footer.html
  kiosko/parts/header.html
  kiosko/parts/mini-cart.html
  kiosko/parts/post-meta.html
  kiosko/patterns/404.php
  kiosko/patterns/comments.php
  kiosko/patterns/footer.php
  kiosko/patterns/hidden-no-results.php
  kiosko/patterns/masthead.php
  kiosko/patterns/no-results-content.php
  kiosko/patterns/post-list.php
  kiosko/patterns/product-filters.php
  kiosko/patterns/product-grid.php
  kiosko/patterns/related-products.php
  kiosko/patterns/site-notice.php
  kiosko/readme.txt
  kiosko/screenshot.png
  kiosko/style.css
  kiosko/templates/404.html
  kiosko/templates/archive-product.html
  kiosko/templates/archive.html
  kiosko/templates/front-page.html
  kiosko/templates/index.html
  kiosko/templates/page.html
  kiosko/templates/product-search-results.html
  kiosko/templates/search.html
  kiosko/templates/single-product.html
  kiosko/templates/single.html
  kiosko/theme.json
Labels: [Status] Needs Design Approval

#7760 Radcliffe 2: Removes logo resize reset testing code
  radcliffe-2/inc/logo-resizer.php
Labels: [Theme ]Radcliffe 2

#7773 Radcliffe 2 & Photos: Revert SVG icon files
  photos/icons/svg-icons.svg
  radcliffe-2/assets/images/icons.svg
Labels: Lego Maintenance

#7778 Workflow security issue
  .github/scripts/create-preview-links.js
  .github/workflows/preview-theme.yml
  adventurer/patterns/404.php
Labels: [Type] Bug

#7783 Dara: move away from deprecated class
  dara/inc/jetpack.php
Labels: [Pri] Low, [Theme] Dara

#7787 Craftfully: Fix for missing "foreground" preset color
  craftfully/patterns/404.php
  craftfully/patterns/footer.php
  craftfully/patterns/header.php
  craftfully/patterns/newsletter-subscription.php
  craftfully/patterns/sidebar.php
  craftfully/templates/search.html
Labels: Lego Maintenance
